import { FormControl, FormGroup } from '@angular/forms';

export type ThirdPageForm = {
  topInfoForSpellSheet: FormGroup<TopInfoForSpellSheetForm>;
  professionForm: FormGroup<ProfessionForm>;
  spellsForm: FormGroup<SpellsForm>;
};

export type TopInfoForSpellSheetForm = {
  jmenoPostavy: FormControl<string | undefined>;
  stupenPozic: FormControl<string | undefined>;
  checkbox1: FormControl<string | undefined>;
  checkbox2: FormControl<string | undefined>;
  checkbox3: FormControl<string | undefined>;
  checkbox4: FormControl<string | undefined>;
  mystickyTaj: FormControl<string | undefined>;
  mystickyTajCheckbox1: FormControl<string | undefined>;
  mystickyTajCheckbox2: FormControl<string | undefined>;
  mystickyTajCheckbox3: FormControl<string | undefined>;
  mystickyTajCheckbox4: FormControl<string | undefined>;
};

export type ProfessionForm = {
  prvniPovolaniSesilatelskePovolani: FormControl<string | undefined>;
  prvniPovolaniUroven: FormControl<string | undefined>;
  prvniPovolaniMaxStupenKouzel: FormControl<string | undefined>;
  prvniPovolaniSesilaciVlastnost: FormControl<string | undefined>;
  prvniPovolaniSOZachrany: FormControl<string | undefined>;
  prvniPovolaniUtocnyBonus: FormControl<string | undefined>;

  druhePovolaniSesilatelskePovolani: FormControl<string | undefined>;
  druhePovolaniUroven: FormControl<string | undefined>;
  druhePovolaniMaxStupenKouzel: FormControl<string | undefined>;
  druhePovolaniSesilaciVlastnost: FormControl<string | undefined>;
  druhePovolaniSOZachrany: FormControl<string | undefined>;
  druhePovolaniUtocnyBonus: FormControl<string | undefined>;
};

export type SpellsForm = {
  r1P: FormControl<string | undefined>;
  r1S: FormControl<string | undefined>;
  r1Nazev: FormControl<string | undefined>;
  r1Utok: FormControl<string | undefined>;
  r1DobaSesilani: FormControl<string | undefined>;
  r1Slozky: FormControl<string | undefined>;
  r1Dosah: FormControl<string | undefined>;
  r1Trvani: FormControl<string | undefined>;
  r1Poznamka: FormControl<string | undefined>;
  r1Str: FormControl<string | undefined>;

  r2P: FormControl<string | undefined>;
  r2S: FormControl<string | undefined>;
  r2Nazev: FormControl<string | undefined>;
  r2Utok: FormControl<string | undefined>;
  r2DobaSesilani: FormControl<string | undefined>;
  r2Slozky: FormControl<string | undefined>;
  r2Dosah: FormControl<string | undefined>;
  r2Trvani: FormControl<string | undefined>;
  r2Poznamka: FormControl<string | undefined>;
  r2Str: FormControl<string | undefined>;

  r3P: FormControl<string | undefined>;
  r3S: FormControl<string | undefined>;
  r3Nazev: FormControl<string | undefined>;
  r3Utok: FormControl<string | undefined>;
  r3DobaSesilani: FormControl<string | undefined>;
  r3Slozky: FormControl<string | undefined>;
  r3Dosah: FormControl<string | undefined>;
  r3Trvani: FormControl<string | undefined>;
  r3Poznamka: FormControl<string | undefined>;
  r3Str: FormControl<string | undefined>;

  r4P: FormControl<string | undefined>;
  r4S: FormControl<string | undefined>;
  r4Nazev: FormControl<string | undefined>;
  r4Utok: FormControl<string | undefined>;
  r4DobaSesilani: FormControl<string | undefined>;
  r4Slozky: FormControl<string | undefined>;
  r4Dosah: FormControl<string | undefined>;
  r4Trvani: FormControl<string | undefined>;
  r4Poznamka: FormControl<string | undefined>;
  r4Str: FormControl<string | undefined>;

  r5P: FormControl<string | undefined>;
  r5S: FormControl<string | undefined>;
  r5Nazev: FormControl<string | undefined>;
  r5Utok: FormControl<string | undefined>;
  r5DobaSesilani: FormControl<string | undefined>;
  r5Slozky: FormControl<string | undefined>;
  r5Dosah: FormControl<string | undefined>;
  r5Trvani: FormControl<string | undefined>;
  r5Poznamka: FormControl<string | undefined>;
  r5Str: FormControl<string | undefined>;

  r6P: FormControl<string | undefined>;
  r6S: FormControl<string | undefined>;
  r6Nazev: FormControl<string | undefined>;
  r6Utok: FormControl<string | undefined>;
  r6DobaSesilani: FormControl<string | undefined>;
  r6Slozky: FormControl<string | undefined>;
  r6Dosah: FormControl<string | undefined>;
  r6Trvani: FormControl<string | undefined>;
  r6Poznamka: FormControl<string | undefined>;
  r6Str: FormControl<string | undefined>;

  r7P: FormControl<string | undefined>;
  r7S: FormControl<string | undefined>;
  r7Nazev: FormControl<string | undefined>;
  r7Utok: FormControl<string | undefined>;
  r7DobaSesilani: FormControl<string | undefined>;
  r7Slozky: FormControl<string | undefined>;
  r7Dosah: FormControl<string | undefined>;
  r7Trvani: FormControl<string | undefined>;
  r7Poznamka: FormControl<string | undefined>;
  r7Str: FormControl<string | undefined>;

  r8P: FormControl<string | undefined>;
  r8S: FormControl<string | undefined>;
  r8Nazev: FormControl<string | undefined>;
  r8Utok: FormControl<string | undefined>;
  r8DobaSesilani: FormControl<string | undefined>;
  r8Slozky: FormControl<string | undefined>;
  r8Dosah: FormControl<string | undefined>;
  r8Trvani: FormControl<string | undefined>;
  r8Poznamka: FormControl<string | undefined>;
  r8Str: FormControl<string | undefined>;

  r9P: FormControl<string | undefined>;
  r9S: FormControl<string | undefined>;
  r9Nazev: FormControl<string | undefined>;
  r9Utok: FormControl<string | undefined>;
  r9DobaSesilani: FormControl<string | undefined>;
  r9Slozky: FormControl<string | undefined>;
  r9Dosah: FormControl<string | undefined>;
  r9Trvani: FormControl<string | undefined>;
  r9Poznamka: FormControl<string | undefined>;
  r9Str: FormControl<string | undefined>;

  r10P: FormControl<string | undefined>;
  r10S: FormControl<string | undefined>;
  r10Nazev: FormControl<string | undefined>;
  r10Utok: FormControl<string | undefined>;
  r10DobaSesilani: FormControl<string | undefined>;
  r10Slozky: FormControl<string | undefined>;
  r10Dosah: FormControl<string | undefined>;
  r10Trvani: FormControl<string | undefined>;
  r10Poznamka: FormControl<string | undefined>;
  r10Str: FormControl<string | undefined>;

  r11P: FormControl<string | undefined>;
  r11S: FormControl<string | undefined>;
  r11Nazev: FormControl<string | undefined>;
  r11Utok: FormControl<string | undefined>;
  r11DobaSesilani: FormControl<string | undefined>;
  r11Slozky: FormControl<string | undefined>;
  r11Dosah: FormControl<string | undefined>;
  r11Trvani: FormControl<string | undefined>;
  r11Poznamka: FormControl<string | undefined>;
  r11Str: FormControl<string | undefined>;
  r12P: FormControl<string | undefined>;
  r12S: FormControl<string | undefined>;
  r12Nazev: FormControl<string | undefined>;
  r12Utok: FormControl<string | undefined>;
  r12DobaSesilani: FormControl<string | undefined>;
  r12Slozky: FormControl<string | undefined>;
  r12Dosah: FormControl<string | undefined>;
  r12Trvani: FormControl<string | undefined>;
  r12Poznamka: FormControl<string | undefined>;
  r12Str: FormControl<string | undefined>;
  r13P: FormControl<string | undefined>;
  r13S: FormControl<string | undefined>;
  r13Nazev: FormControl<string | undefined>;
  r13Utok: FormControl<string | undefined>;
  r13DobaSesilani: FormControl<string | undefined>;
  r13Slozky: FormControl<string | undefined>;
  r13Dosah: FormControl<string | undefined>;
  r13Trvani: FormControl<string | undefined>;
  r13Poznamka: FormControl<string | undefined>;
  r13Str: FormControl<string | undefined>;
  r14P: FormControl<string | undefined>;
  r14S: FormControl<string | undefined>;
  r14Nazev: FormControl<string | undefined>;
  r14Utok: FormControl<string | undefined>;
  r14DobaSesilani: FormControl<string | undefined>;
  r14Slozky: FormControl<string | undefined>;
  r14Dosah: FormControl<string | undefined>;
  r14Trvani: FormControl<string | undefined>;
  r14Poznamka: FormControl<string | undefined>;
  r14Str: FormControl<string | undefined>;
  r15P: FormControl<string | undefined>;
  r15S: FormControl<string | undefined>;
  r15Nazev: FormControl<string | undefined>;
  r15Utok: FormControl<string | undefined>;
  r15DobaSesilani: FormControl<string | undefined>;
  r15Slozky: FormControl<string | undefined>;
  r15Dosah: FormControl<string | undefined>;
  r15Trvani: FormControl<string | undefined>;
  r15Poznamka: FormControl<string | undefined>;
  r15Str: FormControl<string | undefined>;
  r16P: FormControl<string | undefined>;
  r16S: FormControl<string | undefined>;
  r16Nazev: FormControl<string | undefined>;
  r16Utok: FormControl<string | undefined>;
  r16DobaSesilani: FormControl<string | undefined>;
  r16Slozky: FormControl<string | undefined>;
  r16Dosah: FormControl<string | undefined>;
  r16Trvani: FormControl<string | undefined>;
  r16Poznamka: FormControl<string | undefined>;
  r16Str: FormControl<string | undefined>;
  r17P: FormControl<string | undefined>;
  r17S: FormControl<string | undefined>;
  r17Nazev: FormControl<string | undefined>;
  r17Utok: FormControl<string | undefined>;
  r17DobaSesilani: FormControl<string | undefined>;
  r17Slozky: FormControl<string | undefined>;
  r17Dosah: FormControl<string | undefined>;
  r17Trvani: FormControl<string | undefined>;
  r17Poznamka: FormControl<string | undefined>;
  r17Str: FormControl<string | undefined>;
  r18P: FormControl<string | undefined>;
  r18S: FormControl<string | undefined>;
  r18Nazev: FormControl<string | undefined>;
  r18Utok: FormControl<string | undefined>;
  r18DobaSesilani: FormControl<string | undefined>;
  r18Slozky: FormControl<string | undefined>;
  r18Dosah: FormControl<string | undefined>;
  r18Trvani: FormControl<string | undefined>;
  r18Poznamka: FormControl<string | undefined>;
  r18Str: FormControl<string | undefined>;
  r19P: FormControl<string | undefined>;
  r19S: FormControl<string | undefined>;
  r19Nazev: FormControl<string | undefined>;
  r19Utok: FormControl<string | undefined>;
  r19DobaSesilani: FormControl<string | undefined>;
  r19Slozky: FormControl<string | undefined>;
  r19Dosah: FormControl<string | undefined>;
  r19Trvani: FormControl<string | undefined>;
  r19Poznamka: FormControl<string | undefined>;
  r19Str: FormControl<string | undefined>;
  r20P: FormControl<string | undefined>;
  r20S: FormControl<string | undefined>;
  r20Nazev: FormControl<string | undefined>;
  r20Utok: FormControl<string | undefined>;
  r20DobaSesilani: FormControl<string | undefined>;
  r20Slozky: FormControl<string | undefined>;
  r20Dosah: FormControl<string | undefined>;
  r20Trvani: FormControl<string | undefined>;
  r20Poznamka: FormControl<string | undefined>;
  r20Str: FormControl<string | undefined>;
  r21P: FormControl<string | undefined>;
  r21S: FormControl<string | undefined>;
  r21Nazev: FormControl<string | undefined>;
  r21Utok: FormControl<string | undefined>;
  r21DobaSesilani: FormControl<string | undefined>;
  r21Slozky: FormControl<string | undefined>;
  r21Dosah: FormControl<string | undefined>;
  r21Trvani: FormControl<string | undefined>;
  r21Poznamka: FormControl<string | undefined>;
  r21Str: FormControl<string | undefined>;
  r22P: FormControl<string | undefined>;
  r22S: FormControl<string | undefined>;
  r22Nazev: FormControl<string | undefined>;
  r22Utok: FormControl<string | undefined>;
  r22DobaSesilani: FormControl<string | undefined>;
  r22Slozky: FormControl<string | undefined>;
  r22Dosah: FormControl<string | undefined>;
  r22Trvani: FormControl<string | undefined>;
  r22Poznamka: FormControl<string | undefined>;
  r22Str: FormControl<string | undefined>;
  r23P: FormControl<string | undefined>;
  r23S: FormControl<string | undefined>;
  r23Nazev: FormControl<string | undefined>;
  r23Utok: FormControl<string | undefined>;
  r23DobaSesilani: FormControl<string | undefined>;
  r23Slozky: FormControl<string | undefined>;
  r23Dosah: FormControl<string | undefined>;
  r23Trvani: FormControl<string | undefined>;
  r23Poznamka: FormControl<string | undefined>;
  r23Str: FormControl<string | undefined>;
  r24P: FormControl<string | undefined>;
  r24S: FormControl<string | undefined>;
  r24Nazev: FormControl<string | undefined>;
  r24Utok: FormControl<string | undefined>;
  r24DobaSesilani: FormControl<string | undefined>;
  r24Slozky: FormControl<string | undefined>;
  r24Dosah: FormControl<string | undefined>;
  r24Trvani: FormControl<string | undefined>;
  r24Poznamka: FormControl<string | undefined>;
  r24Str: FormControl<string | undefined>;
  r25P: FormControl<string | undefined>;
  r25S: FormControl<string | undefined>;
  r25Nazev: FormControl<string | undefined>;
  r25Utok: FormControl<string | undefined>;
  r25DobaSesilani: FormControl<string | undefined>;
  r25Slozky: FormControl<string | undefined>;
  r25Dosah: FormControl<string | undefined>;
  r25Trvani: FormControl<string | undefined>;
  r25Poznamka: FormControl<string | undefined>;
  r25Str: FormControl<string | undefined>;
  r26P: FormControl<string | undefined>;
  r26S: FormControl<string | undefined>;
  r26Nazev: FormControl<string | undefined>;
  r26Utok: FormControl<string | undefined>;
  r26DobaSesilani: FormControl<string | undefined>;
  r26Slozky: FormControl<string | undefined>;
  r26Dosah: FormControl<string | undefined>;
  r26Trvani: FormControl<string | undefined>;
  r26Poznamka: FormControl<string | undefined>;
  r26Str: FormControl<string | undefined>;
  r27P: FormControl<string | undefined>;
  r27S: FormControl<string | undefined>;
  r27Nazev: FormControl<string | undefined>;
  r27Utok: FormControl<string | undefined>;
  r27DobaSesilani: FormControl<string | undefined>;
  r27Slozky: FormControl<string | undefined>;
  r27Dosah: FormControl<string | undefined>;
  r27Trvani: FormControl<string | undefined>;
  r27Poznamka: FormControl<string | undefined>;
  r27Str: FormControl<string | undefined>;
  r28P: FormControl<string | undefined>;
  r28S: FormControl<string | undefined>;
  r28Nazev: FormControl<string | undefined>;
  r28Utok: FormControl<string | undefined>;
  r28DobaSesilani: FormControl<string | undefined>;
  r28Slozky: FormControl<string | undefined>;
  r28Dosah: FormControl<string | undefined>;
  r28Trvani: FormControl<string | undefined>;
  r28Poznamka: FormControl<string | undefined>;
  r28Str: FormControl<string | undefined>;
  r29P: FormControl<string | undefined>;
  r29S: FormControl<string | undefined>;
  r29Nazev: FormControl<string | undefined>;
  r29Utok: FormControl<string | undefined>;
  r29DobaSesilani: FormControl<string | undefined>;
  r29Slozky: FormControl<string | undefined>;
  r29Dosah: FormControl<string | undefined>;
  r29Trvani: FormControl<string | undefined>;
  r29Poznamka: FormControl<string | undefined>;
  r29Str: FormControl<string | undefined>;
  r30P: FormControl<string | undefined>;
  r30S: FormControl<string | undefined>;
  r30Nazev: FormControl<string | undefined>;
  r30Utok: FormControl<string | undefined>;
  r30DobaSesilani: FormControl<string | undefined>;
  r30Slozky: FormControl<string | undefined>;
  r30Dosah: FormControl<string | undefined>;
  r30Trvani: FormControl<string | undefined>;
  r30Poznamka: FormControl<string | undefined>;
  r30Str: FormControl<string | undefined>;
  r31P: FormControl<string | undefined>;
  r31S: FormControl<string | undefined>;
  r31Nazev: FormControl<string | undefined>;
  r31Utok: FormControl<string | undefined>;
  r31DobaSesilani: FormControl<string | undefined>;
  r31Slozky: FormControl<string | undefined>;
  r31Dosah: FormControl<string | undefined>;
  r31Trvani: FormControl<string | undefined>;
  r31Poznamka: FormControl<string | undefined>;
  r31Str: FormControl<string | undefined>;
  r32P: FormControl<string | undefined>;
  r32S: FormControl<string | undefined>;
  r32Nazev: FormControl<string | undefined>;
  r32Utok: FormControl<string | undefined>;
  r32DobaSesilani: FormControl<string | undefined>;
  r32Slozky: FormControl<string | undefined>;
  r32Dosah: FormControl<string | undefined>;
  r32Trvani: FormControl<string | undefined>;
  r32Poznamka: FormControl<string | undefined>;
  r32Str: FormControl<string | undefined>;
  r33P: FormControl<string | undefined>;
  r33S: FormControl<string | undefined>;
  r33Nazev: FormControl<string | undefined>;
  r33Utok: FormControl<string | undefined>;
  r33DobaSesilani: FormControl<string | undefined>;
  r33Slozky: FormControl<string | undefined>;
  r33Dosah: FormControl<string | undefined>;
  r33Trvani: FormControl<string | undefined>;
  r33Poznamka: FormControl<string | undefined>;
  r33Str: FormControl<string | undefined>;
  r34P: FormControl<string | undefined>;
  r34S: FormControl<string | undefined>;
  r34Nazev: FormControl<string | undefined>;
  r34Utok: FormControl<string | undefined>;
  r34DobaSesilani: FormControl<string | undefined>;
  r34Slozky: FormControl<string | undefined>;
  r34Dosah: FormControl<string | undefined>;
  r34Trvani: FormControl<string | undefined>;
  r34Poznamka: FormControl<string | undefined>;
  r34Str: FormControl<string | undefined>;
  r35P: FormControl<string | undefined>;
  r35S: FormControl<string | undefined>;
  r35Nazev: FormControl<string | undefined>;
  r35Utok: FormControl<string | undefined>;
  r35DobaSesilani: FormControl<string | undefined>;
  r35Slozky: FormControl<string | undefined>;
  r35Dosah: FormControl<string | undefined>;
  r35Trvani: FormControl<string | undefined>;
  r35Poznamka: FormControl<string | undefined>;
  r35Str: FormControl<string | undefined>;
};

export type ThirdPageApiModel = {
  topInfoForSpellSheet: {
    jmenoPostavy: string;
    stupenPozic: string;
    checkbox1: string;
    checkbox2: string;
    checkbox3: string;
    checkbox4: string;
    mystickyTaj: string;
    mystickyTajCheckbox1: string;
    mystickyTajCheckbox2: string;
    mystickyTajCheckbox3: string;
    mystickyTajCheckbox4: string;
  };
  professionForm: {
    prvniPovolaniSesilatelskePovolani: string;
    prvniPovolaniUroven: string;
    prvniPovolaniMaxStupenKouzel: string;
    prvniPovolaniSesilaciVlastnost: string;
    prvniPovolaniSOZachrany: string;
    prvniPovolaniUtocnyBonus: string;

    druhePovolaniSesilatelskePovolani: string;
    druhePovolaniUroven: string;
    druhePovolaniMaxStupenKouzel: string;
    druhePovolaniSesilaciVlastnost: string;
    druhePovolaniSOZachrany: string;
    druhePovolaniUtocnyBonus: string;
  };
  spellsForm: {
    r1P: string;
    r1S: string;
    r1Nazev: string;
    r1Utok: string;
    r1DobaSesilani: string;
    r1Slozky: string;
    r1Dosah: string;
    r1Trvani: string;
    r1Poznamka: string;
    r1Str: string;

    r2P: string;
    r2S: string;
    r2Nazev: string;
    r2Utok: string;
    r2DobaSesilani: string;
    r2Slozky: string;
    r2Dosah: string;
    r2Trvani: string;
    r2Poznamka: string;
    r2Str: string;

    r3P: string;
    r3S: string;
    r3Nazev: string;
    r3Utok: string;
    r3DobaSesilani: string;
    r3Slozky: string;
    r3Dosah: string;
    r3Trvani: string;
    r3Poznamka: string;
    r3Str: string;

    r4P: string;
    r4S: string;
    r4Nazev: string;
    r4Utok: string;
    r4DobaSesilani: string;
    r4Slozky: string;
    r4Dosah: string;
    r4Trvani: string;
    r4Poznamka: string;
    r4Str: string;

    r5P: string;
    r5S: string;
    r5Nazev: string;
    r5Utok: string;
    r5DobaSesilani: string;
    r5Slozky: string;
    r5Dosah: string;
    r5Trvani: string;
    r5Poznamka: string;
    r5Str: string;

    r6P: string;
    r6S: string;
    r6Nazev: string;
    r6Utok: string;
    r6DobaSesilani: string;
    r6Slozky: string;
    r6Dosah: string;
    r6Trvani: string;
    r6Poznamka: string;
    r6Str: string;

    r7P: string;
    r7S: string;
    r7Nazev: string;
    r7Utok: string;
    r7DobaSesilani: string;
    r7Slozky: string;
    r7Dosah: string;
    r7Trvani: string;
    r7Poznamka: string;
    r7Str: string;

    r8P: string;
    r8S: string;
    r8Nazev: string;
    r8Utok: string;
    r8DobaSesilani: string;
    r8Slozky: string;
    r8Dosah: string;
    r8Trvani: string;
    r8Poznamka: string;
    r8Str: string;

    r9P: string;
    r9S: string;
    r9Nazev: string;
    r9Utok: string;
    r9DobaSesilani: string;
    r9Slozky: string;
    r9Dosah: string;
    r9Trvani: string;
    r9Poznamka: string;
    r9Str: string;

    r10P: string;
    r10S: string;
    r10Nazev: string;
    r10Utok: string;
    r10DobaSesilani: string;
    r10Slozky: string;
    r10Dosah: string;
    r10Trvani: string;
    r10Poznamka: string;
    r10Str: string;

    r11P: string;
    r11S: string;
    r11Nazev: string;
    r11Utok: string;
    r11DobaSesilani: string;
    r11Slozky: string;
    r11Dosah: string;
    r11Trvani: string;
    r11Poznamka: string;
    r11Str: string;
    r12P: string;
    r12S: string;
    r12Nazev: string;
    r12Utok: string;
    r12DobaSesilani: string;
    r12Slozky: string;
    r12Dosah: string;
    r12Trvani: string;
    r12Poznamka: string;
    r12Str: string;
    r13P: string;
    r13S: string;
    r13Nazev: string;
    r13Utok: string;
    r13DobaSesilani: string;
    r13Slozky: string;
    r13Dosah: string;
    r13Trvani: string;
    r13Poznamka: string;
    r13Str: string;
    r14P: string;
    r14S: string;
    r14Nazev: string;
    r14Utok: string;
    r14DobaSesilani: string;
    r14Slozky: string;
    r14Dosah: string;
    r14Trvani: string;
    r14Poznamka: string;
    r14Str: string;
    r15P: string;
    r15S: string;
    r15Nazev: string;
    r15Utok: string;
    r15DobaSesilani: string;
    r15Slozky: string;
    r15Dosah: string;
    r15Trvani: string;
    r15Poznamka: string;
    r15Str: string;
    r16P: string;
    r16S: string;
    r16Nazev: string;
    r16Utok: string;
    r16DobaSesilani: string;
    r16Slozky: string;
    r16Dosah: string;
    r16Trvani: string;
    r16Poznamka: string;
    r16Str: string;
    r17P: string;
    r17S: string;
    r17Nazev: string;
    r17Utok: string;
    r17DobaSesilani: string;
    r17Slozky: string;
    r17Dosah: string;
    r17Trvani: string;
    r17Poznamka: string;
    r17Str: string;
    r18P: string;
    r18S: string;
    r18Nazev: string;
    r18Utok: string;
    r18DobaSesilani: string;
    r18Slozky: string;
    r18Dosah: string;
    r18Trvani: string;
    r18Poznamka: string;
    r18Str: string;
    r19P: string;
    r19S: string;
    r19Nazev: string;
    r19Utok: string;
    r19DobaSesilani: string;
    r19Slozky: string;
    r19Dosah: string;
    r19Trvani: string;
    r19Poznamka: string;
    r19Str: string;
    r20P: string;
    r20S: string;
    r20Nazev: string;
    r20Utok: string;
    r20DobaSesilani: string;
    r20Slozky: string;
    r20Dosah: string;
    r20Trvani: string;
    r20Poznamka: string;
    r20Str: string;
    r21P: string;
    r21S: string;
    r21Nazev: string;
    r21Utok: string;
    r21DobaSesilani: string;
    r21Slozky: string;
    r21Dosah: string;
    r21Trvani: string;
    r21Poznamka: string;
    r21Str: string;
    r22P: string;
    r22S: string;
    r22Nazev: string;
    r22Utok: string;
    r22DobaSesilani: string;
    r22Slozky: string;
    r22Dosah: string;
    r22Trvani: string;
    r22Poznamka: string;
    r22Str: string;
    r23P: string;
    r23S: string;
    r23Nazev: string;
    r23Utok: string;
    r23DobaSesilani: string;
    r23Slozky: string;
    r23Dosah: string;
    r23Trvani: string;
    r23Poznamka: string;
    r23Str: string;
    r24P: string;
    r24S: string;
    r24Nazev: string;
    r24Utok: string;
    r24DobaSesilani: string;
    r24Slozky: string;
    r24Dosah: string;
    r24Trvani: string;
    r24Poznamka: string;
    r24Str: string;
    r25P: string;
    r25S: string;
    r25Nazev: string;
    r25Utok: string;
    r25DobaSesilani: string;
    r25Slozky: string;
    r25Dosah: string;
    r25Trvani: string;
    r25Poznamka: string;
    r25Str: string;
    r26P: string;
    r26S: string;
    r26Nazev: string;
    r26Utok: string;
    r26DobaSesilani: string;
    r26Slozky: string;
    r26Dosah: string;
    r26Trvani: string;
    r26Poznamka: string;
    r26Str: string;
    r27P: string;
    r27S: string;
    r27Nazev: string;
    r27Utok: string;
    r27DobaSesilani: string;
    r27Slozky: string;
    r27Dosah: string;
    r27Trvani: string;
    r27Poznamka: string;
    r27Str: string;
    r28P: string;
    r28S: string;
    r28Nazev: string;
    r28Utok: string;
    r28DobaSesilani: string;
    r28Slozky: string;
    r28Dosah: string;
    r28Trvani: string;
    r28Poznamka: string;
    r28Str: string;
    r29P: string;
    r29S: string;
    r29Nazev: string;
    r29Utok: string;
    r29DobaSesilani: string;
    r29Slozky: string;
    r29Dosah: string;
    r29Trvani: string;
    r29Poznamka: string;
    r29Str: string;
    r30P: string;
    r30S: string;
    r30Nazev: string;
    r30Utok: string;
    r30DobaSesilani: string;
    r30Slozky: string;
    r30Dosah: string;
    r30Trvani: string;
    r30Poznamka: string;
    r30Str: string;
    r31P: string;
    r31S: string;
    r31Nazev: string;
    r31Utok: string;
    r31DobaSesilani: string;
    r31Slozky: string;
    r31Dosah: string;
    r31Trvani: string;
    r31Poznamka: string;
    r31Str: string;
    r32P: string;
    r32S: string;
    r32Nazev: string;
    r32Utok: string;
    r32DobaSesilani: string;
    r32Slozky: string;
    r32Dosah: string;
    r32Trvani: string;
    r32Poznamka: string;
    r32Str: string;
    r33P: string;
    r33S: string;
    r33Nazev: string;
    r33Utok: string;
    r33DobaSesilani: string;
    r33Slozky: string;
    r33Dosah: string;
    r33Trvani: string;
    r33Poznamka: string;
    r33Str: string;
    r34P: string;
    r34S: string;
    r34Nazev: string;
    r34Utok: string;
    r34DobaSesilani: string;
    r34Slozky: string;
    r34Dosah: string;
    r34Trvani: string;
    r34Poznamka: string;
    r34Str: string;
    r35P: string;
    r35S: string;
    r35Nazev: string;
    r35Utok: string;
    r35DobaSesilani: string;
    r35Slozky: string;
    r35Dosah: string;
    r35Trvani: string;
    r35Poznamka: string;
    r35Str: string;
  };
};
