/**
 * Each entry is [monsterTitle, bookId, fileName].
 * bookId + fileName are used to load the markdown from `/dnd5esrd/{bookId}/{fileName}`.
 */
export type JadMonsterEntry = readonly [title: string, bookId: string, file: string];

/**
 * Czech monster names extracted from the JaD wiki bestiary and supplements.
 * Sorted alphabetically (Czech locale).
 */
export const JAD_MONSTER_ENTRIES: readonly JadMonsterEntry[] = [
  ['Abolet', 'bestiar', 'abolet.md'],
  ['Alfagryk', 'bestiar', 'gryk.md'],
  ['Allosaurus', 'bestiar', 'dinosauri.md'],
  ['Androsfinga', 'bestiar', 'sfingy.md'],
  ['Ankheg', 'bestiar', 'ankheg.md'],
  ['Ankylosaurus', 'bestiar', 'dinosauri.md'],
  ['Árakokra', 'bestiar', 'arakokra.md'],
  ['Azer', 'bestiar', 'azer.md'],
  ['Bahenní mefit', 'bestiar', 'mefiti.md'],
  ['Balor', 'bestiar', 'demoni.md'],
  ['Bandrhob', 'voluv-pruvodce-netvory', 'Bandrhob.md'],
  ['Barlgura', 'bestiar', 'demoni.md'],
  ['Bazilišek', 'bestiar', 'bazilisek.md'],
  ['Behir', 'bestiar', 'behir.md'],
  ['Bílé dráče', 'bestiar', 'draci.md'],
  ['Blekotající tlamáč', 'bestiar', 'blekotajici-tlamac.md'],
  ['Bludička', 'bestiar', 'bludicka.md'],
  ['Bouřný obr', 'bestiar', 'obri.md'],
  ['Bronzové dráče', 'bestiar', 'draci.md'],
  ['Bulta', 'bestiar', 'bulta.md'],
  ['Černé dráče', 'bestiar', 'draci.md'],
  ['Černý pudink', 'bestiar', 'slizy.md'],
  ['Čistokrevný yuan-ti', 'bestiar', 'yuan-tiove.md'],
  ['Ďáblík', 'bestiar', 'dablove.md'],
  ['Dao', 'bestiar', 'geniove.md'],
  ['Déva', 'bestiar', 'andele.md'],
  ['Diblík', 'bestiar', 'diblik.md'],
  ['Divous', 'bestiar', 'divous.md'],
  ['Dohlížeč', 'bestiar', 'zrici.md'],
  ['Dospělý bílý drak', 'bestiar', 'draci.md'],
  ['Dospělý bronzový drak', 'bestiar', 'draci.md'],
  ['Dospělý černý drak', 'bestiar', 'draci.md'],
  ['Dospělý měděný drak', 'bestiar', 'draci.md'],
  ['Dospělý modrý drak', 'bestiar', 'draci.md'],
  ['Dospělý modrý drakostěj', 'bestiar', 'drakostej.md'],
  ['Dospělý mosazný drak', 'bestiar', 'draci.md'],
  ['Dospělý rudý drak', 'bestiar', 'draci.md'],
  ['Dospělý stříbrný drak', 'bestiar', 'draci.md'],
  ['Dospělý zelený drak', 'bestiar', 'draci.md'],
  ['Dospělý zlatý drak', 'bestiar', 'draci.md'],
  ['Dráč', 'bestiar', 'demoni.md'],
  ['Dračí želva', 'bestiar', 'draci-zelva.md'],
  ['Dravouk', 'bestiar', 'dravouk.md'],
  ['Drow', 'bestiar', 'elfove-drowove.md'],
  ['Drowí elitní válečník', 'bestiar', 'elfove-drowove.md'],
  ['Drowí Lolthina kněžka', 'bestiar', 'elfove-drowove.md'],
  ['Drowí mág', 'bestiar', 'elfove-drowove.md'],
  ['Dryáda', 'bestiar', 'dryada.md'],
  ['Duergar', 'bestiar', 'duergar.md'],
  ['Duch', 'bestiar', 'duch.md'],
  ['Duodron', 'bestiar', 'modroni.md'],
  ['Dusící běhoun', 'bestiar', 'ozivle-predmety.md'],
  ['Dvojník', 'bestiar', 'dvojnik.md'],
  ['Džin', 'bestiar', 'geniove.md'],
  ['Empyrean', 'bestiar', 'empyrean.md'],
  ['Ent', 'bestiar', 'ent.md'],
  ['Erínyje', 'bestiar', 'dablove.md'],
  ['Etin', 'bestiar', 'etin.md'],
  ['Fext', 'bestiar', 'fext.md'],
  ['Fialová houba', 'bestiar', 'houby.md'],
  ['Flamp', 'bestiar', 'flamp.md'],
  ['Fomorian', 'bestiar', 'fomorian.md'],
  ['Galeb dur', 'bestiar', 'galeb-dur.md'],
  ['Ghast', 'bestiar', 'ghulove.md'],
  ['Ghúl', 'bestiar', 'ghulove.md'],
  ['Githyankský rytíř', 'bestiar', 'githove.md'],
  ['Githyankský válečník', 'bestiar', 'githove.md'],
  ['Githzerajský mnich', 'bestiar', 'githove.md'],
  ['Githzerajský zerth', 'bestiar', 'githove.md'],
  ['Glabrezu', 'bestiar', 'demoni.md'],
  ['Gnol', 'bestiar', 'gnolove.md'],
  ['Gnolí Yeenoghuův tesák', 'bestiar', 'gnolove.md'],
  ['Gnóm, hlubinný (permoník)', 'bestiar', 'gnom-hlubinny.md'],
  ['Goblin', 'bestiar', 'goblini.md'],
  ['Gobliní vůdce', 'bestiar', 'goblini.md'],
  ['Gobr', 'bestiar', 'gobri.md'],
  ['Gobří vůdce', 'bestiar', 'gobri.md'],
  ['Gorgon', 'bestiar', 'gorgon.md'],
  ['Goristro', 'bestiar', 'demoni.md'],
  ['Grel', 'bestiar', 'grel.md'],
  ['Gryf', 'bestiar', 'gryf.md'],
  ['Gryk', 'bestiar', 'gryk.md'],
  ['Gynosfinga', 'bestiar', 'sfingy.md'],
  ['Hákovec', 'bestiar', 'hakovec.md'],
  ['Harpyje', 'bestiar', 'harpyje.md'],
  ['Hezr', 'bestiar', 'demoni.md'],
  ['Hipogryf', 'bestiar', 'hipogryf.md'],
  ['Hliněný golem', 'bestiar', 'golemove.md'],
  ['Homunkulus', 'bestiar', 'homunkulus.md'],
  ['Hrotoun', 'bestiar', 'hrotoun.md'],
  ['Hydra', 'bestiar', 'hydra.md'],
  ['Chazma', 'bestiar', 'demoni.md'],
  ['Chiméra', 'bestiar', 'chimera.md'],
  ['Chrlič', 'bestiar', 'chrlic.md'],
  ['Chuul', 'bestiar', 'chuul.md'],
  ['Ifrít', 'bestiar', 'geniove.md'],
  ['Jednorožec', 'bestiar', 'jednorozec.md'],
  ['Jehličnatá sněť', 'bestiar', 'sneti.md'],
  ['Ještěrec', 'bestiar', 'jesterci.md'],
  ['Ještěrecký král/královna', 'bestiar', 'jesterci.md'],
  ['Ještěrecký šaman', 'bestiar', 'jesterci.md'],
  ['Jochlola', 'bestiar', 'demoni.md'],
  ['Kambion', 'bestiar', 'kambion.md'],
  ['Kamenný golem', 'bestiar', 'golemove.md'],
  ['Kamenný obr', 'bestiar', 'obri.md'],
  ['Kancodlak', 'bestiar', 'lykantropove.md'],
  ['Kenku', 'bestiar', 'kenku.md'],
  ['Kentaur', 'bestiar', 'kentaur.md'],
  ['Klamopard', 'bestiar', 'klamopard.md'],
  ['Klepetnatec', 'bestiar', 'klepetnatec.md'],
  ['Kobold', 'bestiar', 'koboldi.md'],
  ['Kokatrice', 'bestiar', 'kokatrice.md'],
  ['Kopcový obr', 'bestiar', 'obri.md'],
  ['Kostěj', 'bestiar', 'kostej.md'],
  ['Kostěná nága', 'bestiar', 'nagy.md'],
  ['Kostěný ďábel', 'bestiar', 'dablove.md'],
  ['Kostlivec', 'bestiar', 'kostlivci.md'],
  ['Kostlivec válečného koně', 'bestiar', 'kostlivci.md'],
  ['Kouřový mefit', 'bestiar', 'mefiti.md'],
  ['Kovatl', 'bestiar', 'kovatl.md'],
  ['Kraken', 'bestiar', 'kraken.md'],
  ['Krápnitec', 'bestiar', 'krapnitec.md'],
  ['Krysodlak', 'bestiar', 'lykantropove.md'],
  ['Kuo-toa', 'bestiar', 'kuo-toove.md'],
  ['Kuo-toovský arcikněz', 'bestiar', 'kuo-toove.md'],
  ['Kuo-toovský práskač', 'bestiar', 'kuo-toove.md'],
  ['Kvadron', 'bestiar', 'modroni.md'],
  ['Kyklop', 'bestiar', 'kyklop.md'],
  ['Lamie', 'bestiar', 'lamie.md'],
  ['Ledový ďábel', 'bestiar', 'dablove.md'],
  ['Ledový mefit', 'bestiar', 'mefiti.md'],
  ['Létající meč', 'bestiar', 'ozivle-predmety.md'],
  ['Lítice', 'bestiar', 'litice.md'],
  ['Magmar', 'bestiar', 'magmar.md'],
  ['Magmatický mefit', 'bestiar', 'mefiti.md'],
  ['Mantikora', 'bestiar', 'mantikora.md'],
  ['Marid', 'bestiar', 'geniove.md'],
  ['Marilita', 'bestiar', 'demoni.md'],
  ['Masný golem', 'bestiar', 'golemove.md'],
  ['Mátoha', 'bestiar', 'dablove.md'],
  ['Měděné dráče', 'bestiar', 'draci.md'],
  ['Medúza', 'bestiar', 'meduza.md'],
  ['Medvědodlak', 'bestiar', 'lykantropove.md'],
  ['Mezzolot', 'bestiar', 'yugoloti.md'],
  ['Mimik', 'bestiar', 'mimik.md'],
  ['Minotaurus', 'bestiar', 'minotaurus.md'],
  ['Minotauří kostlivec', 'bestiar', 'kostlivci.md'],
  ['Mladý bílý drak', 'bestiar', 'draci.md'],
  ['Mladý bronzový drak', 'bestiar', 'draci.md'],
  ['Mladý černý drak', 'bestiar', 'draci.md'],
  ['Mladý měděný drak', 'bestiar', 'draci.md'],
  ['Mladý modrý drak', 'bestiar', 'draci.md'],
  ['Mladý mosazný drak', 'bestiar', 'draci.md'],
  ['Mladý remoráz', 'bestiar', 'remorazove.md'],
  ['Mladý rudý drak', 'bestiar', 'draci.md'],
  ['Mladý rudý stínový drak', 'bestiar', 'drak-stinovy.md'],
  ['Mladý stříbrný drak', 'bestiar', 'draci.md'],
  ['Mladý zelený drak', 'bestiar', 'draci.md'],
  ['Mladý zlatý drak', 'bestiar', 'draci.md'],
  ['Modré dráče', 'bestiar', 'draci.md'],
  ['Modrý slád', 'bestiar', 'sladi.md'],
  ['Monodron', 'bestiar', 'modroni.md'],
  ['Morian', 'bestiar', 'morian.md'],
  ['Mořan', 'bestiar', 'moran.md'],
  ['Mořská ježibaba', 'bestiar', 'jezibaby.md'],
  ['Mosazné dráče', 'bestiar', 'draci.md'],
  ['Mozkožrout', 'bestiar', 'mozkozrout.md'],
  ['Mrazivý obr', 'bestiar', 'obri.md'],
  ['Mrchodravec', 'bestiar', 'mrchodravec.md'],
  ['Mrtvolný tyran', 'bestiar', 'zrici.md'],
  ['Mstitel', 'bestiar', 'mstitel.md'],
  ['Mumie', 'bestiar', 'mumie.md'],
  ['Mykonidí dospělý', 'bestiar', 'mykonidi.md'],
  ['Mykonidí mladík', 'bestiar', 'mykonidi.md'],
  ['Mykonidí panovník', 'bestiar', 'mykonidi.md'],
  ['Mystikolot', 'bestiar', 'yugoloti.md'],
  ['Nalfešný', 'bestiar', 'demoni.md'],
  ['Neviditelný stopař', 'bestiar', 'neviditelny-stopar.md'],
  ['Noční ježibaba', 'bestiar', 'jezibaby.md'],
  ['Noční můra', 'bestiar', 'nocni-mura.md'],
  ['Noh', 'bestiar', 'noh.md'],
  ['Notik', 'bestiar', 'notik.md'],
  ['Nykalot', 'bestiar', 'yugoloti.md'],
  ['Oblačný obr', 'bestiar', 'obri.md'],
  ['Obrněný děs', 'bestiar', 'obrneny-des.md'],
  ['Odporný yetti', 'bestiar', 'yettiove.md'],
  ['Ohavný yuan-ti', 'bestiar', 'yuan-tiove.md'],
  ['Ohnivá lebka', 'bestiar', 'ohniva-lebka.md'],
  ['Ohnivý elementál', 'bestiar', 'elementalove.md'],
  ['Ohnivý had', 'bestiar', 'salamandri.md'],
  ['Ohnivý obr', 'bestiar', 'obri.md'],
  ['Okrový rosol', 'bestiar', 'slizy.md'],
  ['Okřídlený kobold', 'bestiar', 'koboldi.md'],
  ['Ón', 'bestiar', 'on.md'],
  ['Orčí Grúmšovo oko', 'bestiar', 'orkove.md'],
  ['Orčí náčelník', 'bestiar', 'orkove.md'],
  ['Ork', 'bestiar', 'orkove.md'],
  ['Orog', 'bestiar', 'orkove.md'],
  ['Ostnatý ďábel', 'bestiar', 'dablove.md'],
  ['Otyugh', 'bestiar', 'otyugh.md'],
  ['Oživlá zbroj', 'bestiar', 'ozivle-predmety.md'],
  ['Parní mefit', 'bestiar', 'mefiti.md'],
  ['Pavoučnatec', 'bestiar', 'pavoucnatec.md'],
  ['Pegas', 'bestiar', 'pegas.md'],
  ['Pekelný ohař', 'bestiar', 'pekelny-ohar.md'],
  ['Pentadron', 'bestiar', 'modroni.md'],
  ['Peryton', 'bestiar', 'peryton.md'],
  ['Planetár', 'bestiar', 'andele.md'],
  ['Pláštník', 'bestiar', 'plastnik.md'],
  ['Plazivý pařát', 'bestiar', 'plazivy-parat.md'],
  ['Plesiosaurus', 'bestiar', 'dinosauri.md'],
  ['Poletucha', 'bestiar', 'poletucha.md'],
  ['Polokostěj', 'bestiar', 'polokostej.md'],
  ['Polozlobr', 'bestiar', 'zlobri.md'],
  ['Prastarý bílý drak', 'bestiar', 'draci.md'],
  ['Prastarý bronzový drak', 'bestiar', 'draci.md'],
  ['Prastarý černý drak', 'bestiar', 'draci.md'],
  ['Prastarý měděný drak', 'bestiar', 'draci.md'],
  ['Prastarý modrý drak', 'bestiar', 'draci.md'],
  ['Prastarý mosazný drak', 'bestiar', 'draci.md'],
  ['Prastarý rudý drak', 'bestiar', 'draci.md'],
  ['Prastarý stříbrný drak', 'bestiar', 'draci.md'],
  ['Prastarý zelený drak', 'bestiar', 'draci.md'],
  ['Prastarý zlatý drak', 'bestiar', 'draci.md'],
  ['Prašný mefit', 'bestiar', 'mefiti.md'],
  ['Proklatý yuan-ti', 'bestiar', 'yuan-tiove.md'],
  ['Přízračná nága', 'bestiar', 'nagy.md'],
  ['Přízrak', 'bestiar', 'prizrak.md'],
  ['Pseudodrak', 'bestiar', 'pseudodrak.md'],
  ['Pteranodon', 'bestiar', 'dinosauri.md'],
  ['Purpurový červ', 'bestiar', 'purpurovy-cerv.md'],
  ['Quagot', 'bestiar', 'quagot.md'],
  ['Quagotí sporový služebník', 'bestiar', 'mykonidi.md'],
  ['Rakšáza', 'bestiar', 'raksaza.md'],
  ['Rarach', 'bestiar', 'demoni.md'],
  ['Remoráz', 'bestiar', 'remorazove.md'],
  ['Révová sněť', 'bestiar', 'sneti.md'],
  ['Rohatý ďábel', 'bestiar', 'dablove.md'],
  ['Ropušák', 'bestiar', 'ropusak.md'],
  ['Rosolová krychle', 'bestiar', 'slizy.md'],
  ['Rozumhlt', 'bestiar', 'rozumhlt.md'],
  ['Rudé dráče', 'bestiar', 'draci.md'],
  ['Rudý polodračí veterán', 'bestiar', 'polodrak.md'],
  ['Rudý slád', 'bestiar', 'sladi.md'],
  ['Rytíř smrti', 'bestiar', 'rytir-smrti.md'],
  ['Rzivý netvor', 'bestiar', 'rzivy-netvor.md'],
  ['Řetězový ďábel', 'bestiar', 'dablove.md'],
  ['Sahuagin', 'bestiar', 'sahuagini.md'],
  ['Sahuaginská kněžka', 'bestiar', 'sahuagini.md'],
  ['Sahuaginský baron', 'bestiar', 'sahuagini.md'],
  ['Salamandr', 'bestiar', 'salamandri.md'],
  ['Satyr', 'bestiar', 'satyr.md'],
  ['Skurut', 'bestiar', 'skuruti.md'],
  ['Skurutí kapitán', 'bestiar', 'skuruti.md'],
  ['Skurutí vojvoda', 'bestiar', 'skuruti.md'],
  ['Sládový pulec', 'bestiar', 'sladi.md'],
  ['Smrtící slád', 'bestiar', 'sladi.md'],
  ['Solár', 'bestiar', 'andele.md'],
  ['Sovodvěd', 'bestiar', 'sovodved.md'],
  ['Spektra', 'bestiar', 'spektra.md'],
  ['Stal', 'bestiar', 'demoni.md'],
  ['Stín', 'bestiar', 'stin.md'],
  ['Stínový démon', 'bestiar', 'demoni.md'],
  ['Strašák', 'bestiar', 'strasak.md'],
  ['Strážná nága', 'bestiar', 'nagy.md'],
  ['Striga', 'bestiar', 'striga.md'],
  ['Stříbrné dráče', 'bestiar', 'draci.md'],
  ['Sukuba nebo inkubus', 'bestiar', 'sukuba-nebo-inkubus.md'],
  ['Šakalodlak', 'bestiar', 'sakalodlak.md'],
  ['Šedý slád', 'bestiar', 'sladi.md'],
  ['Šedý sliz', 'bestiar', 'slizy.md'],
  ['Šejtán', 'bestiar', 'dablove.md'],
  ['Štítový strážce', 'bestiar', 'stitovy-strazce.md'],
  ['Tarask', 'bestiar', 'tarask.md'],
  ['Temnoplášť', 'bestiar', 'temnoplast.md'],
  ['Thri-kreen', 'bestiar', 'thri-kreen.md'],
  ['Tlející valivec', 'bestiar', 'tlejici-valivec.md'],
  ['Triceratops', 'bestiar', 'dinosauri.md'],
  ['Tridron', 'bestiar', 'modroni.md'],
  ['Trnitý ďábel', 'bestiar', 'dablove.md'],
  ['Troglodyt', 'bestiar', 'troglodyt.md'],
  ['Troll', 'bestiar', 'troll.md'],
  ['Tygrodlak', 'bestiar', 'lykantropove.md'],
  ['Tyranosaurus Rex', 'bestiar', 'dinosauri.md'],
  ['Ultrolot', 'bestiar', 'yugoloti.md'],
  ['Upír', 'bestiar', 'upiri.md'],
  ['Upíří zplozenec', 'bestiar', 'upiri.md'],
  ['Větevní sněť', 'bestiar', 'sneti.md'],
  ['Vílí dráček', 'bestiar', 'vili-dracek.md'],
  ['Vlkodlak', 'bestiar', 'lykantropove.md'],
  ['Vodní div', 'bestiar', 'vodni-div.md'],
  ['Vodní elementál', 'bestiar', 'elementalove.md'],
  ['Vousatý ďábel', 'bestiar', 'dablove.md'],
  ['Vrok', 'bestiar', 'demoni.md'],
  ['Vřesk', 'bestiar', 'houby.md'],
  ['Vůdce gnolí smečky', 'bestiar', 'gnolove.md'],
  ['Výtrusnice', 'bestiar', 'houby.md'],
  ['Vyverna', 'bestiar', 'vyverna.md'],
  ['Vzdušný elementál', 'bestiar', 'elementalove.md'],
  ['Vznešená mumie', 'bestiar', 'mumie.md'],
  ['Xorn', 'bestiar', 'xorn.md'],
  ['Yetti', 'bestiar', 'yettiove.md'],
  ['Zelená ježibaba', 'bestiar', 'jezibaby.md'],
  ['Zelené dráče', 'bestiar', 'draci.md'],
  ['Zelený slád', 'bestiar', 'sladi.md'],
  ['Zemní elementál', 'bestiar', 'elementalove.md'],
  ['Zlaté dráče', 'bestiar', 'draci.md'],
  ['Zlobr', 'bestiar', 'zlobri.md'],
  ['Zlobří zombie', 'bestiar', 'zombie.md'],
  ['Zombie', 'bestiar', 'zombie.md'],
  ['Zřící', 'bestiar', 'zrici.md'],
  ['Zřící zombie', 'bestiar', 'zombie.md'],
  ['Železný golem', 'bestiar', 'golemove.md'],
] as const;

/** Just the monster names (for autocomplete). */
export const JAD_MONSTER_NAMES: readonly string[] = JAD_MONSTER_ENTRIES.map(e => e[0]);

/** Lookup map: lowercase monster name → [bookId, file] */
export const JAD_MONSTER_MAP = new Map<string, { bookId: string; file: string }>(
  JAD_MONSTER_ENTRIES.map(([title, bookId, file]) => [title.toLowerCase(), { bookId, file }]),
);

