import { FormMapper } from '@dn-d-servant/util';
import { CharacterSheetApiModel, CharacterSheetFormData } from '../../../util/src/lib/character-sheet-form';

export class CharacterSheetFormModelMappers {
  static characterSheetFormToApiMapper: FormMapper<CharacterSheetFormData, CharacterSheetApiModel> = {
    twoWayBindings: {
      'topInfo.rasa': 'topInfo.rasa',
      'topInfo.povolani': 'topInfo.povolani',
      'topInfo.zazemi': 'topInfo.zazemi',
      'topInfo.presvedceni': 'topInfo.presvedceni',
      'topInfo.jmenoPostavy': 'topInfo.jmenoPostavy',
      'topInfo.uroven': 'topInfo.uroven',
      'topInfo.zkusenosti': 'topInfo.zkusenosti',
      'topInfo.hrac': 'topInfo.hrac',

      'abilityBonus.zdatnostniBonus': 'abilityBonus.zdatnostniBonus',
      'abilityBonus.inspirace': 'abilityBonus.inspirace',
      'abilityBonus.iniciativa': 'abilityBonus.iniciativa',

      'speedAndHealingDices.lehke': 'speedAndHealingDices.lehke',
      'speedAndHealingDices.stredni': 'speedAndHealingDices.stredni',
      'speedAndHealingDices.tezke': 'speedAndHealingDices.tezke',
      'speedAndHealingDices.pouzitiKostek': 'speedAndHealingDices.pouzitiKostek',
      'speedAndHealingDices.maxPouzitiKostek': 'speedAndHealingDices.maxPouzitiKostek',
      'speedAndHealingDices.smrtUspech1': 'speedAndHealingDices.smrtUspech1',
      'speedAndHealingDices.smrtUspech2': 'speedAndHealingDices.smrtUspech2',
      'speedAndHealingDices.smrtUspech3': 'speedAndHealingDices.smrtUspech3',
      'speedAndHealingDices.smrtNeuspech1': 'speedAndHealingDices.smrtNeuspech1',
      'speedAndHealingDices.smrtNeuspech2': 'speedAndHealingDices.smrtNeuspech2',
      'speedAndHealingDices.smrtNeuspech3': 'speedAndHealingDices.smrtNeuspech3',
      'speedAndHealingDices.maxBoduVydrze': 'speedAndHealingDices.maxBoduVydrze',

      infoAboutCharacter: 'infoAboutCharacter',

      'armorClass.zbroj': 'armorClass.zbroj',
      'armorClass.bezeZbroje': 'armorClass.bezeZbroje',
      'armorClass.jine': 'armorClass.jine',
      'armorClass.zdatnostLehke': 'armorClass.zdatnostLehke',
      'armorClass.zdatnostStredni': 'armorClass.zdatnostStredni',
      'armorClass.zdatnostTezke': 'armorClass.zdatnostTezke',
      'armorClass.zdatnostStity': 'armorClass.zdatnostStity',

      'savingThrowsForm.silaZdatnost': 'savingThrowsForm.silaZdatnost',
      'savingThrowsForm.sila': 'savingThrowsForm.sila',
      'savingThrowsForm.obratnostZdatnost': 'savingThrowsForm.obratnostZdatnost',
      'savingThrowsForm.obratnost': 'savingThrowsForm.obratnost',
      'savingThrowsForm.odolnostZdatnost': 'savingThrowsForm.odolnostZdatnost',
      'savingThrowsForm.odolnost': 'savingThrowsForm.odolnost',
      'savingThrowsForm.inteligenceZdatnost': 'savingThrowsForm.inteligenceZdatnost',
      'savingThrowsForm.inteligence': 'savingThrowsForm.inteligence',
      'savingThrowsForm.moudrostZdatnost': 'savingThrowsForm.moudrostZdatnost',
      'savingThrowsForm.moudrost': 'savingThrowsForm.moudrost',
      'savingThrowsForm.charismaZdatnost': 'savingThrowsForm.charismaZdatnost',
      'savingThrowsForm.charisma': 'savingThrowsForm.charisma', // these two lines problematic

      'passiveSkillsForm.atletikaZdatnost': 'passiveSkillsForm.atletikaZdatnost',
      'passiveSkillsForm.atletika': 'passiveSkillsForm.atletika',
      'passiveSkillsForm.akrobacieZdatnost': 'passiveSkillsForm.akrobacieZdatnost',
      'passiveSkillsForm.akrobacie': 'passiveSkillsForm.akrobacie',
      'passiveSkillsForm.nenapadnostZdatnost': 'passiveSkillsForm.nenapadnostZdatnost',
      'passiveSkillsForm.nenapadnost': 'passiveSkillsForm.nenapadnost',
      'passiveSkillsForm.vhledZdatnost': 'passiveSkillsForm.vhledZdatnost',
      'passiveSkillsForm.vhled': 'passiveSkillsForm.vhled',
      'passiveSkillsForm.vnimaniZdatnost': 'passiveSkillsForm.vnimaniZdatnost',
      'passiveSkillsForm.vnimani': 'passiveSkillsForm.vnimani',
      'passiveSkillsForm.jineZdatnost': 'passiveSkillsForm.jineZdatnost',
      'passiveSkillsForm.jineNazev': 'passiveSkillsForm.jineNazev',
      'passiveSkillsForm.jine': 'passiveSkillsForm.jine',

      // todo: spell slots and alchemist chest
      'spellsAndAlchemistChestForm.vlastnost': 'spellsAndAlchemistChestForm.vlastnost',
      'spellsAndAlchemistChestForm.utBonus': 'spellsAndAlchemistChestForm.utBonus',
      'spellsAndAlchemistChestForm.soZachrany': 'spellsAndAlchemistChestForm.soZachrany',

      'main6SkillsForm.silaOprava': 'main6SkillsForm.silaOprava',
      'main6SkillsForm.sila': 'main6SkillsForm.sila',
      'main6SkillsForm.obratnostOprava': 'main6SkillsForm.obratnostOprava',
      'main6SkillsForm.obratnost': 'main6SkillsForm.obratnost',
      'main6SkillsForm.odolnostOprava': 'main6SkillsForm.odolnostOprava',
      'main6SkillsForm.odolnost': 'main6SkillsForm.odolnost',
      'main6SkillsForm.inteligenceOprava': 'main6SkillsForm.inteligenceOprava',
      'main6SkillsForm.inteligence': 'main6SkillsForm.inteligence',
      'main6SkillsForm.moudrostOprava': 'main6SkillsForm.moudrostOprava',
      'main6SkillsForm.moudrost': 'main6SkillsForm.moudrost',
      'main6SkillsForm.charismaOprava': 'main6SkillsForm.charismaOprava',
      'main6SkillsForm.charisma': 'main6SkillsForm.charisma',

      'abilitiesForm.atletikaZdatnost': 'abilitiesForm.atletikaZdatnost',
      'abilitiesForm.atletika': 'abilitiesForm.atletika',
      'abilitiesForm.akrobacieZdatnost': 'abilitiesForm.akrobacieZdatnost',
      'abilitiesForm.akrobacie': 'abilitiesForm.akrobacie',
      'abilitiesForm.cachryZdatnost': 'abilitiesForm.cachryZdatnost',
      'abilitiesForm.cachry': 'abilitiesForm.cachry',
      'abilitiesForm.nenapadnostZdatnost': 'abilitiesForm.nenapadnostZdatnost',
      'abilitiesForm.nenapadnost': 'abilitiesForm.nenapadnost',
      'abilitiesForm.historieZdatnost': 'abilitiesForm.historieZdatnost',
      'abilitiesForm.historie': 'abilitiesForm.historie',
      'abilitiesForm.mystikaZdatnost': 'abilitiesForm.mystikaZdatnost',
      'abilitiesForm.mystika': 'abilitiesForm.mystika',
      'abilitiesForm.nabozenstviZdatnost': 'abilitiesForm.nabozenstviZdatnost',
      'abilitiesForm.nabozenstvi': 'abilitiesForm.nabozenstvi',
      'abilitiesForm.patraniZdatnost': 'abilitiesForm.patraniZdatnost',
      'abilitiesForm.patrani': 'abilitiesForm.patrani',
      'abilitiesForm.prirodaZdatnost': 'abilitiesForm.prirodaZdatnost',
      'abilitiesForm.priroda': 'abilitiesForm.priroda',
      'abilitiesForm.lekarstviZdatnost': 'abilitiesForm.lekarstviZdatnost',
      'abilitiesForm.lekarstvi': 'abilitiesForm.lekarstvi',
      'abilitiesForm.ovladaniZviratZdatnost': 'abilitiesForm.ovladaniZviratZdatnost',
      'abilitiesForm.ovladaniZvirat': 'abilitiesForm.ovladaniZvirat',
      'abilitiesForm.prezitiZdatnost': 'abilitiesForm.prezitiZdatnost',
      'abilitiesForm.preziti': 'abilitiesForm.preziti',
      'abilitiesForm.vhledZdatnost': 'abilitiesForm.vhledZdatnost',
      'abilitiesForm.vhled': 'abilitiesForm.vhled',
      'abilitiesForm.vnimaniZdatnost': 'abilitiesForm.vnimaniZdatnost',
      'abilitiesForm.vnimani': 'abilitiesForm.vnimani',
      'abilitiesForm.klamaniZdatnost': 'abilitiesForm.klamaniZdatnost',
      'abilitiesForm.klamani': 'abilitiesForm.klamani',
      'abilitiesForm.presvedcovaniZdatnost': 'abilitiesForm.presvedcovaniZdatnost',
      'abilitiesForm.presvedcovani': 'abilitiesForm.presvedcovani',
      'abilitiesForm.vystupovaniZdatnost': 'abilitiesForm.vystupovaniZdatnost',
      'abilitiesForm.vystupovani': 'abilitiesForm.vystupovani',
      'abilitiesForm.zastrasovaniZdatnost': 'abilitiesForm.zastrasovaniZdatnost',
      'abilitiesForm.zastrasovani': 'abilitiesForm.zastrasovani',

      pomucky: 'pomucky',

      'weaponsForm.zbran1': 'weaponsForm.zbran1',
      'weaponsForm.zbran1Bonus': 'weaponsForm.zbran1Bonus',
      'weaponsForm.zbran1Zasah': 'weaponsForm.zbran1Zasah',
      'weaponsForm.zbran1Typ': 'weaponsForm.zbran1Typ',
      'weaponsForm.zbran1Dosah': 'weaponsForm.zbran1Dosah',
      'weaponsForm.zbran1Oc': 'weaponsForm.zbran1Oc',

      'weaponsForm.zbran2': 'weaponsForm.zbran2',
      'weaponsForm.zbran2Bonus': 'weaponsForm.zbran2Bonus',
      'weaponsForm.zbran2Zasah': 'weaponsForm.zbran2Zasah',
      'weaponsForm.zbran2Typ': 'weaponsForm.zbran2Typ',
      'weaponsForm.zbran2Dosah': 'weaponsForm.zbran2Dosah',
      'weaponsForm.zbran2Oc': 'weaponsForm.zbran2Oc',

      'weaponsForm.zbran3': 'weaponsForm.zbran3',
      'weaponsForm.zbran3Bonus': 'weaponsForm.zbran3Bonus',
      'weaponsForm.zbran3Zasah': 'weaponsForm.zbran3Zasah',
      'weaponsForm.zbran3Typ': 'weaponsForm.zbran3Typ',
      'weaponsForm.zbran3Dosah': 'weaponsForm.zbran3Dosah',
      'weaponsForm.zbran3Oc': 'weaponsForm.zbran3Oc',

      'weaponsForm.zbran4': 'weaponsForm.zbran4',
      'weaponsForm.zbran4Bonus': 'weaponsForm.zbran4Bonus',
      'weaponsForm.zbran4Zasah': 'weaponsForm.zbran4Zasah',
      'weaponsForm.zbran4Typ': 'weaponsForm.zbran4Typ',
      'weaponsForm.zbran4Dosah': 'weaponsForm.zbran4Dosah',
      'weaponsForm.zbran4Oc': 'weaponsForm.zbran4Oc',

      'weaponsForm.zbran5': 'weaponsForm.zbran5',
      'weaponsForm.zbran5Bonus': 'weaponsForm.zbran5Bonus',
      'weaponsForm.zbran5Zasah': 'weaponsForm.zbran5Zasah',
      'weaponsForm.zbran5Typ': 'weaponsForm.zbran5Typ',
      'weaponsForm.zbran5Dosah': 'weaponsForm.zbran5Dosah',
      'weaponsForm.zbran5Oc': 'weaponsForm.zbran5Oc',

      'weaponsForm.zdatnostJednoduche': 'weaponsForm.zdatnostJednoduche',
      'weaponsForm.zdatnostValecne': 'weaponsForm.zdatnostValecne',
      'weaponsForm.dalsiZdatnosti': 'weaponsForm.dalsiZdatnosti',

      'languagesForm.jazyky': 'languagesForm.jazyky',
      'languagesForm.schopnosti': 'languagesForm.schopnosti',

      'inventoryForm.penize': 'inventoryForm.penize',
      'inventoryForm.radek1': 'inventoryForm.radek1',
      'inventoryForm.radek2': 'inventoryForm.radek2',
      'inventoryForm.radek3': 'inventoryForm.radek3',
      'inventoryForm.radek4': 'inventoryForm.radek4',
      'inventoryForm.radek5': 'inventoryForm.radek5',
      'inventoryForm.radek6': 'inventoryForm.radek6',
      'inventoryForm.radek7': 'inventoryForm.radek7',
      'inventoryForm.radek8': 'inventoryForm.radek8',
      'inventoryForm.radek9': 'inventoryForm.radek9',
      'inventoryForm.radek10': 'inventoryForm.radek10',
      'inventoryForm.radek11': 'inventoryForm.radek11',
      'inventoryForm.radek12': 'inventoryForm.radek12',
      'inventoryForm.radek13': 'inventoryForm.radek13',
      'inventoryForm.radek14': 'inventoryForm.radek14',
      'inventoryForm.radek15': 'inventoryForm.radek15',
      'inventoryForm.radek16': 'inventoryForm.radek16',
      'inventoryForm.radek17': 'inventoryForm.radek17',
      'inventoryForm.radek18': 'inventoryForm.radek18',
      'inventoryForm.radek19': 'inventoryForm.radek19',
      'inventoryForm.radek20': 'inventoryForm.radek20',

      // Spell slots
      'spellSlotsForm.urovenSesilatele': 'spellSlotsForm.urovenSesilatele',
      'spellSlotsForm.urovenCernokneznika': 'spellSlotsForm.urovenCernokneznika',
      'spellSlotsForm.level1Slot1': 'spellSlotsForm.level1Slot1',
      'spellSlotsForm.level1Slot2': 'spellSlotsForm.level1Slot2',
      'spellSlotsForm.level1Slot3': 'spellSlotsForm.level1Slot3',
      'spellSlotsForm.level1Slot4': 'spellSlotsForm.level1Slot4',

      'spellSlotsForm.level2Slot1': 'spellSlotsForm.level2Slot1',
      'spellSlotsForm.level2Slot2': 'spellSlotsForm.level2Slot2',
      'spellSlotsForm.level2Slot3': 'spellSlotsForm.level2Slot3',
      'spellSlotsForm.level2Slot4': 'spellSlotsForm.level2Slot4',

      'spellSlotsForm.level3Slot1': 'spellSlotsForm.level3Slot1',
      'spellSlotsForm.level3Slot2': 'spellSlotsForm.level3Slot2',
      'spellSlotsForm.level3Slot3': 'spellSlotsForm.level3Slot3',
      'spellSlotsForm.level3Slot4': 'spellSlotsForm.level3Slot4',

      'spellSlotsForm.level4Slot1': 'spellSlotsForm.level4Slot1',
      'spellSlotsForm.level4Slot2': 'spellSlotsForm.level4Slot2',
      'spellSlotsForm.level4Slot3': 'spellSlotsForm.level4Slot3',
      'spellSlotsForm.level4Slot4': 'spellSlotsForm.level4Slot4',

      'spellSlotsForm.level5Slot1': 'spellSlotsForm.level5Slot1',
      'spellSlotsForm.level5Slot2': 'spellSlotsForm.level5Slot2',
      'spellSlotsForm.level5Slot3': 'spellSlotsForm.level5Slot3',
      'spellSlotsForm.level5Slot4': 'spellSlotsForm.level5Slot4',

      'spellSlotsForm.level6Slot1': 'spellSlotsForm.level6Slot1',
      'spellSlotsForm.level6Slot2': 'spellSlotsForm.level6Slot2',

      'spellSlotsForm.level7Slot1': 'spellSlotsForm.level7Slot1',
      'spellSlotsForm.level7Slot2': 'spellSlotsForm.level7Slot2',

      'spellSlotsForm.level8Slot1': 'spellSlotsForm.level8Slot1',

      'spellSlotsForm.level9Slot1': 'spellSlotsForm.level9Slot1',

      // Alchemist chest
      'alchemistChestForm.urovenAlchymisty': 'alchemistChestForm.urovenAlchymisty',
      'alchemistChestForm.chestUsage1': 'alchemistChestForm.chestUsage1',
      'alchemistChestForm.chestUsage2': 'alchemistChestForm.chestUsage2',
      'alchemistChestForm.chestUsage3': 'alchemistChestForm.chestUsage3',
      'alchemistChestForm.chestUsage4': 'alchemistChestForm.chestUsage4',
      'alchemistChestForm.chestUsage5': 'alchemistChestForm.chestUsage5',
      'alchemistChestForm.chestUsage6': 'alchemistChestForm.chestUsage6',
      'alchemistChestForm.chestUsage7': 'alchemistChestForm.chestUsage7',
      'alchemistChestForm.chestUsage8': 'alchemistChestForm.chestUsage8',
      'alchemistChestForm.chestUsage9': 'alchemistChestForm.chestUsage9',
      'alchemistChestForm.chestUsage10': 'alchemistChestForm.chestUsage10',
      'alchemistChestForm.chestUsage11': 'alchemistChestForm.chestUsage11',
      'alchemistChestForm.chestUsage12': 'alchemistChestForm.chestUsage12',
      'alchemistChestForm.chestUsage13': 'alchemistChestForm.chestUsage13',
      'alchemistChestForm.chestUsage14': 'alchemistChestForm.chestUsage14',
      'alchemistChestForm.chestUsage15': 'alchemistChestForm.chestUsage15',
      'alchemistChestForm.chestUsage16': 'alchemistChestForm.chestUsage16',
      'alchemistChestForm.chestUsage17': 'alchemistChestForm.chestUsage17',
      'alchemistChestForm.chestUsage18': 'alchemistChestForm.chestUsage18',
      'alchemistChestForm.chestUsage19': 'alchemistChestForm.chestUsage19',
      'alchemistChestForm.chestUsage20': 'alchemistChestForm.chestUsage20',

      //------------------ START OF SECOND PAGE ------------------
      'secondPageForm.headerInfo.jmenoPostavy': 'secondPageForm.headerInfo.jmenoPostavy',
      'secondPageForm.headerInfo.titulyAHodnosti': 'secondPageForm.headerInfo.titulyAHodnosti',

      'secondPageForm.lookAndFeelForm.vek': 'secondPageForm.lookAndFeelForm.vek',
      'secondPageForm.lookAndFeelForm.plet': 'secondPageForm.lookAndFeelForm.plet',
      'secondPageForm.lookAndFeelForm.vyska': 'secondPageForm.lookAndFeelForm.vyska',
      'secondPageForm.lookAndFeelForm.vlasy': 'secondPageForm.lookAndFeelForm.vlasy',
      'secondPageForm.lookAndFeelForm.vaha': 'secondPageForm.lookAndFeelForm.vaha',
      'secondPageForm.lookAndFeelForm.oci': 'secondPageForm.lookAndFeelForm.oci',
      'secondPageForm.lookAndFeelForm.postava': 'secondPageForm.lookAndFeelForm.postava',
      'secondPageForm.lookAndFeelForm.obleceniAVzezreni': 'secondPageForm.lookAndFeelForm.obleceniAVzezreni',
      'secondPageForm.lookAndFeelForm.dojemAVystupovani': 'secondPageForm.lookAndFeelForm.dojemAVystupovani',

      'secondPageForm.vztahy': 'secondPageForm.vztahy',
      'secondPageForm.dalsiPoznamky1': 'secondPageForm.dalsiPoznamky1',
      'secondPageForm.dalsiPoznamky2': 'secondPageForm.dalsiPoznamky2',

      //------------------ START OF THIRD PAGE ------------------
      'thirdPageForm.topInfoForSpellSheet.jmenoPostavy': 'thirdPageForm.topInfoForSpellSheet.jmenoPostavy',
      'thirdPageForm.topInfoForSpellSheet.stupenPozic': 'thirdPageForm.topInfoForSpellSheet.stupenPozic',
      'thirdPageForm.topInfoForSpellSheet.checkbox1': 'thirdPageForm.topInfoForSpellSheet.checkbox1',
      'thirdPageForm.topInfoForSpellSheet.checkbox2': 'thirdPageForm.topInfoForSpellSheet.checkbox2',
      'thirdPageForm.topInfoForSpellSheet.checkbox3': 'thirdPageForm.topInfoForSpellSheet.checkbox3',
      'thirdPageForm.topInfoForSpellSheet.checkbox4': 'thirdPageForm.topInfoForSpellSheet.checkbox4',
      'thirdPageForm.topInfoForSpellSheet.mystickyTaj': 'thirdPageForm.topInfoForSpellSheet.mystickyTaj',
      'thirdPageForm.topInfoForSpellSheet.mystickyTajCheckbox1': 'thirdPageForm.topInfoForSpellSheet.mystickyTajCheckbox1',
      'thirdPageForm.topInfoForSpellSheet.mystickyTajCheckbox2': 'thirdPageForm.topInfoForSpellSheet.mystickyTajCheckbox2',
      'thirdPageForm.topInfoForSpellSheet.mystickyTajCheckbox3': 'thirdPageForm.topInfoForSpellSheet.mystickyTajCheckbox3',
      'thirdPageForm.topInfoForSpellSheet.mystickyTajCheckbox4': 'thirdPageForm.topInfoForSpellSheet.mystickyTajCheckbox4',

      'thirdPageForm.professionForm.prvniPovolaniSesilatelskePovolani':
        'thirdPageForm.professionForm.prvniPovolaniSesilatelskePovolani',
      'thirdPageForm.professionForm.prvniPovolaniUroven': 'thirdPageForm.professionForm.prvniPovolaniUroven',
      'thirdPageForm.professionForm.prvniPovolaniMaxStupenKouzel': 'thirdPageForm.professionForm.prvniPovolaniMaxStupenKouzel',
      'thirdPageForm.professionForm.prvniPovolaniSesilaciVlastnost':
        'thirdPageForm.professionForm.prvniPovolaniSesilaciVlastnost',
      'thirdPageForm.professionForm.prvniPovolaniSOZachrany': 'thirdPageForm.professionForm.prvniPovolaniSOZachrany',
      'thirdPageForm.professionForm.prvniPovolaniUtocnyBonus': 'thirdPageForm.professionForm.prvniPovolaniUtocnyBonus',

      'thirdPageForm.professionForm.druhePovolaniSesilatelskePovolani':
        'thirdPageForm.professionForm.druhePovolaniSesilatelskePovolani',
      'thirdPageForm.professionForm.druhePovolaniUroven': 'thirdPageForm.professionForm.druhePovolaniUroven',
      'thirdPageForm.professionForm.druhePovolaniMaxStupenKouzel': 'thirdPageForm.professionForm.druhePovolaniMaxStupenKouzel',
      'thirdPageForm.professionForm.druhePovolaniSesilaciVlastnost':
        'thirdPageForm.professionForm.druhePovolaniSesilaciVlastnost',
      'thirdPageForm.professionForm.druhePovolaniSOZachrany': 'thirdPageForm.professionForm.druhePovolaniSOZachrany',
      'thirdPageForm.professionForm.druhePovolaniUtocnyBonus': 'thirdPageForm.professionForm.druhePovolaniUtocnyBonus',

      // Spells
      'thirdPageForm.spellsForm.r1P': 'thirdPageForm.spellsForm.r1P',
      'thirdPageForm.spellsForm.r1S': 'thirdPageForm.spellsForm.r1S',
      'thirdPageForm.spellsForm.r1Nazev': 'thirdPageForm.spellsForm.r1Nazev',
      'thirdPageForm.spellsForm.r1Utok': 'thirdPageForm.spellsForm.r1Utok',
      'thirdPageForm.spellsForm.r1DobaSesilani': 'thirdPageForm.spellsForm.r1DobaSesilani',
      'thirdPageForm.spellsForm.r1Slozky': 'thirdPageForm.spellsForm.r1Slozky',
      'thirdPageForm.spellsForm.r1Dosah': 'thirdPageForm.spellsForm.r1Dosah',
      'thirdPageForm.spellsForm.r1Trvani': 'thirdPageForm.spellsForm.r1Trvani',
      'thirdPageForm.spellsForm.r1Poznamka': 'thirdPageForm.spellsForm.r1Poznamka',
      'thirdPageForm.spellsForm.r1Str': 'thirdPageForm.spellsForm.r1Str',

      'thirdPageForm.spellsForm.r2P': 'thirdPageForm.spellsForm.r2P',
      'thirdPageForm.spellsForm.r2S': 'thirdPageForm.spellsForm.r2S',
      'thirdPageForm.spellsForm.r2Nazev': 'thirdPageForm.spellsForm.r2Nazev',
      'thirdPageForm.spellsForm.r2Utok': 'thirdPageForm.spellsForm.r2Utok',
      'thirdPageForm.spellsForm.r2DobaSesilani': 'thirdPageForm.spellsForm.r2DobaSesilani',
      'thirdPageForm.spellsForm.r2Slozky': 'thirdPageForm.spellsForm.r2Slozky',
      'thirdPageForm.spellsForm.r2Dosah': 'thirdPageForm.spellsForm.r2Dosah',
      'thirdPageForm.spellsForm.r2Trvani': 'thirdPageForm.spellsForm.r2Trvani',
      'thirdPageForm.spellsForm.r2Poznamka': 'thirdPageForm.spellsForm.r2Poznamka',
      'thirdPageForm.spellsForm.r2Str': 'thirdPageForm.spellsForm.r2Str',

      'thirdPageForm.spellsForm.r3P': 'thirdPageForm.spellsForm.r3P',
      'thirdPageForm.spellsForm.r3S': 'thirdPageForm.spellsForm.r3S',
      'thirdPageForm.spellsForm.r3Nazev': 'thirdPageForm.spellsForm.r3Nazev',
      'thirdPageForm.spellsForm.r3Utok': 'thirdPageForm.spellsForm.r3Utok',
      'thirdPageForm.spellsForm.r3DobaSesilani': 'thirdPageForm.spellsForm.r3DobaSesilani',
      'thirdPageForm.spellsForm.r3Slozky': 'thirdPageForm.spellsForm.r3Slozky',
      'thirdPageForm.spellsForm.r3Dosah': 'thirdPageForm.spellsForm.r3Dosah',
      'thirdPageForm.spellsForm.r3Trvani': 'thirdPageForm.spellsForm.r3Trvani',
      'thirdPageForm.spellsForm.r3Poznamka': 'thirdPageForm.spellsForm.r3Poznamka',
      'thirdPageForm.spellsForm.r3Str': 'thirdPageForm.spellsForm.r3Str',

      'thirdPageForm.spellsForm.r4P': 'thirdPageForm.spellsForm.r4P',
      'thirdPageForm.spellsForm.r4S': 'thirdPageForm.spellsForm.r4S',
      'thirdPageForm.spellsForm.r4Nazev': 'thirdPageForm.spellsForm.r4Nazev',
      'thirdPageForm.spellsForm.r4Utok': 'thirdPageForm.spellsForm.r4Utok',
      'thirdPageForm.spellsForm.r4DobaSesilani': 'thirdPageForm.spellsForm.r4DobaSesilani',
      'thirdPageForm.spellsForm.r4Slozky': 'thirdPageForm.spellsForm.r4Slozky',
      'thirdPageForm.spellsForm.r4Dosah': 'thirdPageForm.spellsForm.r4Dosah',
      'thirdPageForm.spellsForm.r4Trvani': 'thirdPageForm.spellsForm.r4Trvani',
      'thirdPageForm.spellsForm.r4Poznamka': 'thirdPageForm.spellsForm.r4Poznamka',
      'thirdPageForm.spellsForm.r4Str': 'thirdPageForm.spellsForm.r4Str',

      'thirdPageForm.spellsForm.r5P': 'thirdPageForm.spellsForm.r5P',
      'thirdPageForm.spellsForm.r5S': 'thirdPageForm.spellsForm.r5S',
      'thirdPageForm.spellsForm.r5Nazev': 'thirdPageForm.spellsForm.r5Nazev',
      'thirdPageForm.spellsForm.r5Utok': 'thirdPageForm.spellsForm.r5Utok',
      'thirdPageForm.spellsForm.r5DobaSesilani': 'thirdPageForm.spellsForm.r5DobaSesilani',
      'thirdPageForm.spellsForm.r5Slozky': 'thirdPageForm.spellsForm.r5Slozky',
      'thirdPageForm.spellsForm.r5Dosah': 'thirdPageForm.spellsForm.r5Dosah',
      'thirdPageForm.spellsForm.r5Trvani': 'thirdPageForm.spellsForm.r5Trvani',
      'thirdPageForm.spellsForm.r5Poznamka': 'thirdPageForm.spellsForm.r5Poznamka',
      'thirdPageForm.spellsForm.r5Str': 'thirdPageForm.spellsForm.r5Str',

      'thirdPageForm.spellsForm.r6P': 'thirdPageForm.spellsForm.r6P',
      'thirdPageForm.spellsForm.r6S': 'thirdPageForm.spellsForm.r6S',
      'thirdPageForm.spellsForm.r6Nazev': 'thirdPageForm.spellsForm.r6Nazev',
      'thirdPageForm.spellsForm.r6Utok': 'thirdPageForm.spellsForm.r6Utok',
      'thirdPageForm.spellsForm.r6DobaSesilani': 'thirdPageForm.spellsForm.r6DobaSesilani',
      'thirdPageForm.spellsForm.r6Slozky': 'thirdPageForm.spellsForm.r6Slozky',
      'thirdPageForm.spellsForm.r6Dosah': 'thirdPageForm.spellsForm.r6Dosah',
      'thirdPageForm.spellsForm.r6Trvani': 'thirdPageForm.spellsForm.r6Trvani',
      'thirdPageForm.spellsForm.r6Poznamka': 'thirdPageForm.spellsForm.r6Poznamka',
      'thirdPageForm.spellsForm.r6Str': 'thirdPageForm.spellsForm.r6Str',

      'thirdPageForm.spellsForm.r7P': 'thirdPageForm.spellsForm.r7P',
      'thirdPageForm.spellsForm.r7S': 'thirdPageForm.spellsForm.r7S',
      'thirdPageForm.spellsForm.r7Nazev': 'thirdPageForm.spellsForm.r7Nazev',
      'thirdPageForm.spellsForm.r7Utok': 'thirdPageForm.spellsForm.r7Utok',
      'thirdPageForm.spellsForm.r7DobaSesilani': 'thirdPageForm.spellsForm.r7DobaSesilani',
      'thirdPageForm.spellsForm.r7Slozky': 'thirdPageForm.spellsForm.r7Slozky',
      'thirdPageForm.spellsForm.r7Dosah': 'thirdPageForm.spellsForm.r7Dosah',
      'thirdPageForm.spellsForm.r7Trvani': 'thirdPageForm.spellsForm.r7Trvani',
      'thirdPageForm.spellsForm.r7Poznamka': 'thirdPageForm.spellsForm.r7Poznamka',
      'thirdPageForm.spellsForm.r7Str': 'thirdPageForm.spellsForm.r7Str',

      'thirdPageForm.spellsForm.r8P': 'thirdPageForm.spellsForm.r8P',
      'thirdPageForm.spellsForm.r8S': 'thirdPageForm.spellsForm.r8S',
      'thirdPageForm.spellsForm.r8Nazev': 'thirdPageForm.spellsForm.r8Nazev',
      'thirdPageForm.spellsForm.r8Utok': 'thirdPageForm.spellsForm.r8Utok',
      'thirdPageForm.spellsForm.r8DobaSesilani': 'thirdPageForm.spellsForm.r8DobaSesilani',
      'thirdPageForm.spellsForm.r8Slozky': 'thirdPageForm.spellsForm.r8Slozky',
      'thirdPageForm.spellsForm.r8Dosah': 'thirdPageForm.spellsForm.r8Dosah',
      'thirdPageForm.spellsForm.r8Trvani': 'thirdPageForm.spellsForm.r8Trvani',
      'thirdPageForm.spellsForm.r8Poznamka': 'thirdPageForm.spellsForm.r8Poznamka',
      'thirdPageForm.spellsForm.r8Str': 'thirdPageForm.spellsForm.r8Str',

      'thirdPageForm.spellsForm.r9P': 'thirdPageForm.spellsForm.r9P',
      'thirdPageForm.spellsForm.r9S': 'thirdPageForm.spellsForm.r9S',
      'thirdPageForm.spellsForm.r9Nazev': 'thirdPageForm.spellsForm.r9Nazev',
      'thirdPageForm.spellsForm.r9Utok': 'thirdPageForm.spellsForm.r9Utok',
      'thirdPageForm.spellsForm.r9DobaSesilani': 'thirdPageForm.spellsForm.r9DobaSesilani',
      'thirdPageForm.spellsForm.r9Slozky': 'thirdPageForm.spellsForm.r9Slozky',
      'thirdPageForm.spellsForm.r9Dosah': 'thirdPageForm.spellsForm.r9Dosah',
      'thirdPageForm.spellsForm.r9Trvani': 'thirdPageForm.spellsForm.r9Trvani',
      'thirdPageForm.spellsForm.r9Poznamka': 'thirdPageForm.spellsForm.r9Poznamka',
      'thirdPageForm.spellsForm.r9Str': 'thirdPageForm.spellsForm.r9Str',

      'thirdPageForm.spellsForm.r10P': 'thirdPageForm.spellsForm.r10P',
      'thirdPageForm.spellsForm.r10S': 'thirdPageForm.spellsForm.r10S',
      'thirdPageForm.spellsForm.r10Nazev': 'thirdPageForm.spellsForm.r10Nazev',
      'thirdPageForm.spellsForm.r10Utok': 'thirdPageForm.spellsForm.r10Utok',
      'thirdPageForm.spellsForm.r10DobaSesilani': 'thirdPageForm.spellsForm.r10DobaSesilani',
      'thirdPageForm.spellsForm.r10Slozky': 'thirdPageForm.spellsForm.r10Slozky',
      'thirdPageForm.spellsForm.r10Dosah': 'thirdPageForm.spellsForm.r10Dosah',
      'thirdPageForm.spellsForm.r10Trvani': 'thirdPageForm.spellsForm.r10Trvani',
      'thirdPageForm.spellsForm.r10Poznamka': 'thirdPageForm.spellsForm.r10Poznamka',
      'thirdPageForm.spellsForm.r10Str': 'thirdPageForm.spellsForm.r10Str',

      'thirdPageForm.spellsForm.r11P': 'thirdPageForm.spellsForm.r11P',
      'thirdPageForm.spellsForm.r11S': 'thirdPageForm.spellsForm.r11S',
      'thirdPageForm.spellsForm.r11Nazev': 'thirdPageForm.spellsForm.r11Nazev',
      'thirdPageForm.spellsForm.r11Utok': 'thirdPageForm.spellsForm.r11Utok',
      'thirdPageForm.spellsForm.r11DobaSesilani': 'thirdPageForm.spellsForm.r11DobaSesilani',
      'thirdPageForm.spellsForm.r11Slozky': 'thirdPageForm.spellsForm.r11Slozky',
      'thirdPageForm.spellsForm.r11Dosah': 'thirdPageForm.spellsForm.r11Dosah',
      'thirdPageForm.spellsForm.r11Trvani': 'thirdPageForm.spellsForm.r11Trvani',
      'thirdPageForm.spellsForm.r11Poznamka': 'thirdPageForm.spellsForm.r11Poznamka',
      'thirdPageForm.spellsForm.r11Str': 'thirdPageForm.spellsForm.r11Str',
      'thirdPageForm.spellsForm.r12P': 'thirdPageForm.spellsForm.r12P',
      'thirdPageForm.spellsForm.r12S': 'thirdPageForm.spellsForm.r12S',
      'thirdPageForm.spellsForm.r12Nazev': 'thirdPageForm.spellsForm.r12Nazev',
      'thirdPageForm.spellsForm.r12Utok': 'thirdPageForm.spellsForm.r12Utok',
      'thirdPageForm.spellsForm.r12DobaSesilani': 'thirdPageForm.spellsForm.r12DobaSesilani',
      'thirdPageForm.spellsForm.r12Slozky': 'thirdPageForm.spellsForm.r12Slozky',
      'thirdPageForm.spellsForm.r12Dosah': 'thirdPageForm.spellsForm.r12Dosah',
      'thirdPageForm.spellsForm.r12Trvani': 'thirdPageForm.spellsForm.r12Trvani',
      'thirdPageForm.spellsForm.r12Poznamka': 'thirdPageForm.spellsForm.r12Poznamka',
      'thirdPageForm.spellsForm.r12Str': 'thirdPageForm.spellsForm.r12Str',
      'thirdPageForm.spellsForm.r13P': 'thirdPageForm.spellsForm.r13P',
      'thirdPageForm.spellsForm.r13S': 'thirdPageForm.spellsForm.r13S',
      'thirdPageForm.spellsForm.r13Nazev': 'thirdPageForm.spellsForm.r13Nazev',
      'thirdPageForm.spellsForm.r13Utok': 'thirdPageForm.spellsForm.r13Utok',
      'thirdPageForm.spellsForm.r13DobaSesilani': 'thirdPageForm.spellsForm.r13DobaSesilani',
      'thirdPageForm.spellsForm.r13Slozky': 'thirdPageForm.spellsForm.r13Slozky',
      'thirdPageForm.spellsForm.r13Dosah': 'thirdPageForm.spellsForm.r13Dosah',
      'thirdPageForm.spellsForm.r13Trvani': 'thirdPageForm.spellsForm.r13Trvani',
      'thirdPageForm.spellsForm.r13Poznamka': 'thirdPageForm.spellsForm.r13Poznamka',
      'thirdPageForm.spellsForm.r13Str': 'thirdPageForm.spellsForm.r13Str',
      'thirdPageForm.spellsForm.r14P': 'thirdPageForm.spellsForm.r14P',
      'thirdPageForm.spellsForm.r14S': 'thirdPageForm.spellsForm.r14S',
      'thirdPageForm.spellsForm.r14Nazev': 'thirdPageForm.spellsForm.r14Nazev',
      'thirdPageForm.spellsForm.r14Utok': 'thirdPageForm.spellsForm.r14Utok',
      'thirdPageForm.spellsForm.r14DobaSesilani': 'thirdPageForm.spellsForm.r14DobaSesilani',
      'thirdPageForm.spellsForm.r14Slozky': 'thirdPageForm.spellsForm.r14Slozky',
      'thirdPageForm.spellsForm.r14Dosah': 'thirdPageForm.spellsForm.r14Dosah',
      'thirdPageForm.spellsForm.r14Trvani': 'thirdPageForm.spellsForm.r14Trvani',
      'thirdPageForm.spellsForm.r14Poznamka': 'thirdPageForm.spellsForm.r14Poznamka',
      'thirdPageForm.spellsForm.r14Str': 'thirdPageForm.spellsForm.r14Str',
      'thirdPageForm.spellsForm.r15P': 'thirdPageForm.spellsForm.r15P',
      'thirdPageForm.spellsForm.r15S': 'thirdPageForm.spellsForm.r15S',
      'thirdPageForm.spellsForm.r15Nazev': 'thirdPageForm.spellsForm.r15Nazev',
      'thirdPageForm.spellsForm.r15Utok': 'thirdPageForm.spellsForm.r15Utok',
      'thirdPageForm.spellsForm.r15DobaSesilani': 'thirdPageForm.spellsForm.r15DobaSesilani',
      'thirdPageForm.spellsForm.r15Slozky': 'thirdPageForm.spellsForm.r15Slozky',
      'thirdPageForm.spellsForm.r15Dosah': 'thirdPageForm.spellsForm.r15Dosah',
      'thirdPageForm.spellsForm.r15Trvani': 'thirdPageForm.spellsForm.r15Trvani',
      'thirdPageForm.spellsForm.r15Poznamka': 'thirdPageForm.spellsForm.r15Poznamka',
      'thirdPageForm.spellsForm.r15Str': 'thirdPageForm.spellsForm.r15Str',
      'thirdPageForm.spellsForm.r16P': 'thirdPageForm.spellsForm.r16P',
      'thirdPageForm.spellsForm.r16S': 'thirdPageForm.spellsForm.r16S',
      'thirdPageForm.spellsForm.r16Nazev': 'thirdPageForm.spellsForm.r16Nazev',
      'thirdPageForm.spellsForm.r16Utok': 'thirdPageForm.spellsForm.r16Utok',
      'thirdPageForm.spellsForm.r16DobaSesilani': 'thirdPageForm.spellsForm.r16DobaSesilani',
      'thirdPageForm.spellsForm.r16Slozky': 'thirdPageForm.spellsForm.r16Slozky',
      'thirdPageForm.spellsForm.r16Dosah': 'thirdPageForm.spellsForm.r16Dosah',
      'thirdPageForm.spellsForm.r16Trvani': 'thirdPageForm.spellsForm.r16Trvani',
      'thirdPageForm.spellsForm.r16Poznamka': 'thirdPageForm.spellsForm.r16Poznamka',
      'thirdPageForm.spellsForm.r16Str': 'thirdPageForm.spellsForm.r16Str',
      'thirdPageForm.spellsForm.r17P': 'thirdPageForm.spellsForm.r17P',
      'thirdPageForm.spellsForm.r17S': 'thirdPageForm.spellsForm.r17S',
      'thirdPageForm.spellsForm.r17Nazev': 'thirdPageForm.spellsForm.r17Nazev',
      'thirdPageForm.spellsForm.r17Utok': 'thirdPageForm.spellsForm.r17Utok',
      'thirdPageForm.spellsForm.r17DobaSesilani': 'thirdPageForm.spellsForm.r17DobaSesilani',
      'thirdPageForm.spellsForm.r17Slozky': 'thirdPageForm.spellsForm.r17Slozky',
      'thirdPageForm.spellsForm.r17Dosah': 'thirdPageForm.spellsForm.r17Dosah',
      'thirdPageForm.spellsForm.r17Trvani': 'thirdPageForm.spellsForm.r17Trvani',
      'thirdPageForm.spellsForm.r17Poznamka': 'thirdPageForm.spellsForm.r17Poznamka',
      'thirdPageForm.spellsForm.r17Str': 'thirdPageForm.spellsForm.r17Str',
      'thirdPageForm.spellsForm.r18P': 'thirdPageForm.spellsForm.r18P',
      'thirdPageForm.spellsForm.r18S': 'thirdPageForm.spellsForm.r18S',
      'thirdPageForm.spellsForm.r18Nazev': 'thirdPageForm.spellsForm.r18Nazev',
      'thirdPageForm.spellsForm.r18Utok': 'thirdPageForm.spellsForm.r18Utok',
      'thirdPageForm.spellsForm.r18DobaSesilani': 'thirdPageForm.spellsForm.r18DobaSesilani',
      'thirdPageForm.spellsForm.r18Slozky': 'thirdPageForm.spellsForm.r18Slozky',
      'thirdPageForm.spellsForm.r18Dosah': 'thirdPageForm.spellsForm.r18Dosah',
      'thirdPageForm.spellsForm.r18Trvani': 'thirdPageForm.spellsForm.r18Trvani',
      'thirdPageForm.spellsForm.r18Poznamka': 'thirdPageForm.spellsForm.r18Poznamka',
      'thirdPageForm.spellsForm.r18Str': 'thirdPageForm.spellsForm.r18Str',
      'thirdPageForm.spellsForm.r19P': 'thirdPageForm.spellsForm.r19P',
      'thirdPageForm.spellsForm.r19S': 'thirdPageForm.spellsForm.r19S',
      'thirdPageForm.spellsForm.r19Nazev': 'thirdPageForm.spellsForm.r19Nazev',
      'thirdPageForm.spellsForm.r19Utok': 'thirdPageForm.spellsForm.r19Utok',
      'thirdPageForm.spellsForm.r19DobaSesilani': 'thirdPageForm.spellsForm.r19DobaSesilani',
      'thirdPageForm.spellsForm.r19Slozky': 'thirdPageForm.spellsForm.r19Slozky',
      'thirdPageForm.spellsForm.r19Dosah': 'thirdPageForm.spellsForm.r19Dosah',
      'thirdPageForm.spellsForm.r19Trvani': 'thirdPageForm.spellsForm.r19Trvani',
      'thirdPageForm.spellsForm.r19Poznamka': 'thirdPageForm.spellsForm.r19Poznamka',
      'thirdPageForm.spellsForm.r19Str': 'thirdPageForm.spellsForm.r19Str',
      'thirdPageForm.spellsForm.r20P': 'thirdPageForm.spellsForm.r20P',
      'thirdPageForm.spellsForm.r20S': 'thirdPageForm.spellsForm.r20S',
      'thirdPageForm.spellsForm.r20Nazev': 'thirdPageForm.spellsForm.r20Nazev',
      'thirdPageForm.spellsForm.r20Utok': 'thirdPageForm.spellsForm.r20Utok',
      'thirdPageForm.spellsForm.r20DobaSesilani': 'thirdPageForm.spellsForm.r20DobaSesilani',
      'thirdPageForm.spellsForm.r20Slozky': 'thirdPageForm.spellsForm.r20Slozky',
      'thirdPageForm.spellsForm.r20Dosah': 'thirdPageForm.spellsForm.r20Dosah',
      'thirdPageForm.spellsForm.r20Trvani': 'thirdPageForm.spellsForm.r20Trvani',
      'thirdPageForm.spellsForm.r20Poznamka': 'thirdPageForm.spellsForm.r20Poznamka',
      'thirdPageForm.spellsForm.r20Str': 'thirdPageForm.spellsForm.r20Str',
      'thirdPageForm.spellsForm.r21P': 'thirdPageForm.spellsForm.r21P',
      'thirdPageForm.spellsForm.r21S': 'thirdPageForm.spellsForm.r21S',
      'thirdPageForm.spellsForm.r21Nazev': 'thirdPageForm.spellsForm.r21Nazev',
      'thirdPageForm.spellsForm.r21Utok': 'thirdPageForm.spellsForm.r21Utok',
      'thirdPageForm.spellsForm.r21DobaSesilani': 'thirdPageForm.spellsForm.r21DobaSesilani',
      'thirdPageForm.spellsForm.r21Slozky': 'thirdPageForm.spellsForm.r21Slozky',
      'thirdPageForm.spellsForm.r21Dosah': 'thirdPageForm.spellsForm.r21Dosah',
      'thirdPageForm.spellsForm.r21Trvani': 'thirdPageForm.spellsForm.r21Trvani',
      'thirdPageForm.spellsForm.r21Poznamka': 'thirdPageForm.spellsForm.r21Poznamka',
      'thirdPageForm.spellsForm.r21Str': 'thirdPageForm.spellsForm.r21Str',
      'thirdPageForm.spellsForm.r22P': 'thirdPageForm.spellsForm.r22P',
      'thirdPageForm.spellsForm.r22S': 'thirdPageForm.spellsForm.r22S',
      'thirdPageForm.spellsForm.r22Nazev': 'thirdPageForm.spellsForm.r22Nazev',
      'thirdPageForm.spellsForm.r22Utok': 'thirdPageForm.spellsForm.r22Utok',
      'thirdPageForm.spellsForm.r22DobaSesilani': 'thirdPageForm.spellsForm.r22DobaSesilani',
      'thirdPageForm.spellsForm.r22Slozky': 'thirdPageForm.spellsForm.r22Slozky',
      'thirdPageForm.spellsForm.r22Dosah': 'thirdPageForm.spellsForm.r22Dosah',
      'thirdPageForm.spellsForm.r22Trvani': 'thirdPageForm.spellsForm.r22Trvani',
      'thirdPageForm.spellsForm.r22Poznamka': 'thirdPageForm.spellsForm.r22Poznamka',
      'thirdPageForm.spellsForm.r22Str': 'thirdPageForm.spellsForm.r22Str',
      'thirdPageForm.spellsForm.r23P': 'thirdPageForm.spellsForm.r23P',
      'thirdPageForm.spellsForm.r23S': 'thirdPageForm.spellsForm.r23S',
      'thirdPageForm.spellsForm.r23Nazev': 'thirdPageForm.spellsForm.r23Nazev',
      'thirdPageForm.spellsForm.r23Utok': 'thirdPageForm.spellsForm.r23Utok',
      'thirdPageForm.spellsForm.r23DobaSesilani': 'thirdPageForm.spellsForm.r23DobaSesilani',
      'thirdPageForm.spellsForm.r23Slozky': 'thirdPageForm.spellsForm.r23Slozky',
      'thirdPageForm.spellsForm.r23Dosah': 'thirdPageForm.spellsForm.r23Dosah',
      'thirdPageForm.spellsForm.r23Trvani': 'thirdPageForm.spellsForm.r23Trvani',
      'thirdPageForm.spellsForm.r23Poznamka': 'thirdPageForm.spellsForm.r23Poznamka',
      'thirdPageForm.spellsForm.r23Str': 'thirdPageForm.spellsForm.r23Str',
      'thirdPageForm.spellsForm.r24P': 'thirdPageForm.spellsForm.r24P',
      'thirdPageForm.spellsForm.r24S': 'thirdPageForm.spellsForm.r24S',
      'thirdPageForm.spellsForm.r24Nazev': 'thirdPageForm.spellsForm.r24Nazev',
      'thirdPageForm.spellsForm.r24Utok': 'thirdPageForm.spellsForm.r24Utok',
      'thirdPageForm.spellsForm.r24DobaSesilani': 'thirdPageForm.spellsForm.r24DobaSesilani',
      'thirdPageForm.spellsForm.r24Slozky': 'thirdPageForm.spellsForm.r24Slozky',
      'thirdPageForm.spellsForm.r24Dosah': 'thirdPageForm.spellsForm.r24Dosah',
      'thirdPageForm.spellsForm.r24Trvani': 'thirdPageForm.spellsForm.r24Trvani',
      'thirdPageForm.spellsForm.r24Poznamka': 'thirdPageForm.spellsForm.r24Poznamka',
      'thirdPageForm.spellsForm.r24Str': 'thirdPageForm.spellsForm.r24Str',
      'thirdPageForm.spellsForm.r25P': 'thirdPageForm.spellsForm.r25P',
      'thirdPageForm.spellsForm.r25S': 'thirdPageForm.spellsForm.r25S',
      'thirdPageForm.spellsForm.r25Nazev': 'thirdPageForm.spellsForm.r25Nazev',
      'thirdPageForm.spellsForm.r25Utok': 'thirdPageForm.spellsForm.r25Utok',
      'thirdPageForm.spellsForm.r25DobaSesilani': 'thirdPageForm.spellsForm.r25DobaSesilani',
      'thirdPageForm.spellsForm.r25Slozky': 'thirdPageForm.spellsForm.r25Slozky',
      'thirdPageForm.spellsForm.r25Dosah': 'thirdPageForm.spellsForm.r25Dosah',
      'thirdPageForm.spellsForm.r25Trvani': 'thirdPageForm.spellsForm.r25Trvani',
      'thirdPageForm.spellsForm.r25Poznamka': 'thirdPageForm.spellsForm.r25Poznamka',
      'thirdPageForm.spellsForm.r25Str': 'thirdPageForm.spellsForm.r25Str',
      'thirdPageForm.spellsForm.r26P': 'thirdPageForm.spellsForm.r26P',
      'thirdPageForm.spellsForm.r26S': 'thirdPageForm.spellsForm.r26S',
      'thirdPageForm.spellsForm.r26Nazev': 'thirdPageForm.spellsForm.r26Nazev',
      'thirdPageForm.spellsForm.r26Utok': 'thirdPageForm.spellsForm.r26Utok',
      'thirdPageForm.spellsForm.r26DobaSesilani': 'thirdPageForm.spellsForm.r26DobaSesilani',
      'thirdPageForm.spellsForm.r26Slozky': 'thirdPageForm.spellsForm.r26Slozky',
      'thirdPageForm.spellsForm.r26Dosah': 'thirdPageForm.spellsForm.r26Dosah',
      'thirdPageForm.spellsForm.r26Trvani': 'thirdPageForm.spellsForm.r26Trvani',
      'thirdPageForm.spellsForm.r26Poznamka': 'thirdPageForm.spellsForm.r26Poznamka',
      'thirdPageForm.spellsForm.r26Str': 'thirdPageForm.spellsForm.r26Str',
      'thirdPageForm.spellsForm.r27P': 'thirdPageForm.spellsForm.r27P',
      'thirdPageForm.spellsForm.r27S': 'thirdPageForm.spellsForm.r27S',
      'thirdPageForm.spellsForm.r27Nazev': 'thirdPageForm.spellsForm.r27Nazev',
      'thirdPageForm.spellsForm.r27Utok': 'thirdPageForm.spellsForm.r27Utok',
      'thirdPageForm.spellsForm.r27DobaSesilani': 'thirdPageForm.spellsForm.r27DobaSesilani',
      'thirdPageForm.spellsForm.r27Slozky': 'thirdPageForm.spellsForm.r27Slozky',
      'thirdPageForm.spellsForm.r27Dosah': 'thirdPageForm.spellsForm.r27Dosah',
      'thirdPageForm.spellsForm.r27Trvani': 'thirdPageForm.spellsForm.r27Trvani',
      'thirdPageForm.spellsForm.r27Poznamka': 'thirdPageForm.spellsForm.r27Poznamka',
      'thirdPageForm.spellsForm.r27Str': 'thirdPageForm.spellsForm.r27Str',
      'thirdPageForm.spellsForm.r28P': 'thirdPageForm.spellsForm.r28P',
      'thirdPageForm.spellsForm.r28S': 'thirdPageForm.spellsForm.r28S',
      'thirdPageForm.spellsForm.r28Nazev': 'thirdPageForm.spellsForm.r28Nazev',
      'thirdPageForm.spellsForm.r28Utok': 'thirdPageForm.spellsForm.r28Utok',
      'thirdPageForm.spellsForm.r28DobaSesilani': 'thirdPageForm.spellsForm.r28DobaSesilani',
      'thirdPageForm.spellsForm.r28Slozky': 'thirdPageForm.spellsForm.r28Slozky',
      'thirdPageForm.spellsForm.r28Dosah': 'thirdPageForm.spellsForm.r28Dosah',
      'thirdPageForm.spellsForm.r28Trvani': 'thirdPageForm.spellsForm.r28Trvani',
      'thirdPageForm.spellsForm.r28Poznamka': 'thirdPageForm.spellsForm.r28Poznamka',
      'thirdPageForm.spellsForm.r28Str': 'thirdPageForm.spellsForm.r28Str',
      'thirdPageForm.spellsForm.r29P': 'thirdPageForm.spellsForm.r29P',
      'thirdPageForm.spellsForm.r29S': 'thirdPageForm.spellsForm.r29S',
      'thirdPageForm.spellsForm.r29Nazev': 'thirdPageForm.spellsForm.r29Nazev',
      'thirdPageForm.spellsForm.r29Utok': 'thirdPageForm.spellsForm.r29Utok',
      'thirdPageForm.spellsForm.r29DobaSesilani': 'thirdPageForm.spellsForm.r29DobaSesilani',
      'thirdPageForm.spellsForm.r29Slozky': 'thirdPageForm.spellsForm.r29Slozky',
      'thirdPageForm.spellsForm.r29Dosah': 'thirdPageForm.spellsForm.r29Dosah',
      'thirdPageForm.spellsForm.r29Trvani': 'thirdPageForm.spellsForm.r29Trvani',
      'thirdPageForm.spellsForm.r29Poznamka': 'thirdPageForm.spellsForm.r29Poznamka',
      'thirdPageForm.spellsForm.r29Str': 'thirdPageForm.spellsForm.r29Str',
      'thirdPageForm.spellsForm.r30P': 'thirdPageForm.spellsForm.r30P',
      'thirdPageForm.spellsForm.r30S': 'thirdPageForm.spellsForm.r30S',
      'thirdPageForm.spellsForm.r30Nazev': 'thirdPageForm.spellsForm.r30Nazev',
      'thirdPageForm.spellsForm.r30Utok': 'thirdPageForm.spellsForm.r30Utok',
      'thirdPageForm.spellsForm.r30DobaSesilani': 'thirdPageForm.spellsForm.r30DobaSesilani',
      'thirdPageForm.spellsForm.r30Slozky': 'thirdPageForm.spellsForm.r30Slozky',
      'thirdPageForm.spellsForm.r30Dosah': 'thirdPageForm.spellsForm.r30Dosah',
      'thirdPageForm.spellsForm.r30Trvani': 'thirdPageForm.spellsForm.r30Trvani',
      'thirdPageForm.spellsForm.r30Poznamka': 'thirdPageForm.spellsForm.r30Poznamka',
      'thirdPageForm.spellsForm.r30Str': 'thirdPageForm.spellsForm.r30Str',
      'thirdPageForm.spellsForm.r31P': 'thirdPageForm.spellsForm.r31P',
      'thirdPageForm.spellsForm.r31S': 'thirdPageForm.spellsForm.r31S',
      'thirdPageForm.spellsForm.r31Nazev': 'thirdPageForm.spellsForm.r31Nazev',
      'thirdPageForm.spellsForm.r31Utok': 'thirdPageForm.spellsForm.r31Utok',
      'thirdPageForm.spellsForm.r31DobaSesilani': 'thirdPageForm.spellsForm.r31DobaSesilani',
      'thirdPageForm.spellsForm.r31Slozky': 'thirdPageForm.spellsForm.r31Slozky',
      'thirdPageForm.spellsForm.r31Dosah': 'thirdPageForm.spellsForm.r31Dosah',
      'thirdPageForm.spellsForm.r31Trvani': 'thirdPageForm.spellsForm.r31Trvani',
      'thirdPageForm.spellsForm.r31Poznamka': 'thirdPageForm.spellsForm.r31Poznamka',
      'thirdPageForm.spellsForm.r31Str': 'thirdPageForm.spellsForm.r31Str',
      'thirdPageForm.spellsForm.r32P': 'thirdPageForm.spellsForm.r32P',
      'thirdPageForm.spellsForm.r32S': 'thirdPageForm.spellsForm.r32S',
      'thirdPageForm.spellsForm.r32Nazev': 'thirdPageForm.spellsForm.r32Nazev',
      'thirdPageForm.spellsForm.r32Utok': 'thirdPageForm.spellsForm.r32Utok',
      'thirdPageForm.spellsForm.r32DobaSesilani': 'thirdPageForm.spellsForm.r32DobaSesilani',
      'thirdPageForm.spellsForm.r32Slozky': 'thirdPageForm.spellsForm.r32Slozky',
      'thirdPageForm.spellsForm.r32Dosah': 'thirdPageForm.spellsForm.r32Dosah',
      'thirdPageForm.spellsForm.r32Trvani': 'thirdPageForm.spellsForm.r32Trvani',
      'thirdPageForm.spellsForm.r32Poznamka': 'thirdPageForm.spellsForm.r32Poznamka',
      'thirdPageForm.spellsForm.r32Str': 'thirdPageForm.spellsForm.r32Str',
      'thirdPageForm.spellsForm.r33P': 'thirdPageForm.spellsForm.r33P',
      'thirdPageForm.spellsForm.r33S': 'thirdPageForm.spellsForm.r33S',
      'thirdPageForm.spellsForm.r33Nazev': 'thirdPageForm.spellsForm.r33Nazev',
      'thirdPageForm.spellsForm.r33Utok': 'thirdPageForm.spellsForm.r33Utok',
      'thirdPageForm.spellsForm.r33DobaSesilani': 'thirdPageForm.spellsForm.r33DobaSesilani',
      'thirdPageForm.spellsForm.r33Slozky': 'thirdPageForm.spellsForm.r33Slozky',
      'thirdPageForm.spellsForm.r33Dosah': 'thirdPageForm.spellsForm.r33Dosah',
      'thirdPageForm.spellsForm.r33Trvani': 'thirdPageForm.spellsForm.r33Trvani',
      'thirdPageForm.spellsForm.r33Poznamka': 'thirdPageForm.spellsForm.r33Poznamka',
      'thirdPageForm.spellsForm.r33Str': 'thirdPageForm.spellsForm.r33Str',
      'thirdPageForm.spellsForm.r34P': 'thirdPageForm.spellsForm.r34P',
      'thirdPageForm.spellsForm.r34S': 'thirdPageForm.spellsForm.r34S',
      'thirdPageForm.spellsForm.r34Nazev': 'thirdPageForm.spellsForm.r34Nazev',
      'thirdPageForm.spellsForm.r34Utok': 'thirdPageForm.spellsForm.r34Utok',
      'thirdPageForm.spellsForm.r34DobaSesilani': 'thirdPageForm.spellsForm.r34DobaSesilani',
      'thirdPageForm.spellsForm.r34Slozky': 'thirdPageForm.spellsForm.r34Slozky',
      'thirdPageForm.spellsForm.r34Dosah': 'thirdPageForm.spellsForm.r34Dosah',
      'thirdPageForm.spellsForm.r34Trvani': 'thirdPageForm.spellsForm.r34Trvani',
      'thirdPageForm.spellsForm.r34Poznamka': 'thirdPageForm.spellsForm.r34Poznamka',
      'thirdPageForm.spellsForm.r34Str': 'thirdPageForm.spellsForm.r34Str',
      'thirdPageForm.spellsForm.r35P': 'thirdPageForm.spellsForm.r35P',
      'thirdPageForm.spellsForm.r35S': 'thirdPageForm.spellsForm.r35S',
      'thirdPageForm.spellsForm.r35Nazev': 'thirdPageForm.spellsForm.r35Nazev',
      'thirdPageForm.spellsForm.r35Utok': 'thirdPageForm.spellsForm.r35Utok',
      'thirdPageForm.spellsForm.r35DobaSesilani': 'thirdPageForm.spellsForm.r35DobaSesilani',
      'thirdPageForm.spellsForm.r35Slozky': 'thirdPageForm.spellsForm.r35Slozky',
      'thirdPageForm.spellsForm.r35Dosah': 'thirdPageForm.spellsForm.r35Dosah',
      'thirdPageForm.spellsForm.r35Trvani': 'thirdPageForm.spellsForm.r35Trvani',
      'thirdPageForm.spellsForm.r35Poznamka': 'thirdPageForm.spellsForm.r35Poznamka',
      'thirdPageForm.spellsForm.r35Str': 'thirdPageForm.spellsForm.r35Str',
    },
  };
}
