import { FormMapper } from '@dn-d-servant/util';
import {GroupSheetApiModel, GroupSheetFormData} from "@dn-d-servant/character-sheet-util";

export class GroupSheetFormModelMappers {
  static groupSheetFormToApiMapper: FormMapper<GroupSheetFormData, GroupSheetApiModel> = {
    twoWayBindings: {
      jmenoSkupinovehoZazemi: 'jmenoSkupinovehoZazemi',
      typSkupinovehoZazemi: 'typSkupinovehoZazemi',
      jmenoSkupiny: 'jmenoSkupiny',
      zdatnostPriSkupinovemOvereni: 'zdatnostPriSkupinovemOvereni',
      zdatnostSPomuckamiAJazyky: 'zdatnostSPomuckamiAJazyky',
      schopnostSkupinovehoZazemi: 'schopnostSkupinovehoZazemi',
      skupinoveZazemi: 'skupinoveZazemi',
      zvire: 'zvire',
      penize: 'penize',

      'vybava.radek1': 'vybava.radek1',
      'vybava.radek2': 'vybava.radek2',
      'vybava.radek3': 'vybava.radek3',
      'vybava.radek4': 'vybava.radek4',
      'vybava.radek5': 'vybava.radek5',
      'vybava.radek6': 'vybava.radek6',
      'vybava.radek7': 'vybava.radek7',
      'vybava.radek8': 'vybava.radek8',
      'vybava.radek9': 'vybava.radek9',
      'vybava.radek10': 'vybava.radek10',
      'vybava.radek11': 'vybava.radek11',
      'vybava.radek12': 'vybava.radek12',
      'vybava.radek13': 'vybava.radek13',
      'vybava.radek14': 'vybava.radek14',
      'vybava.radek15': 'vybava.radek15',
      'vybava.radek16': 'vybava.radek16',
      'vybava.radek17': 'vybava.radek17',
      'vybava.radek18': 'vybava.radek18',
      'vybava.radek19': 'vybava.radek19',
      'vybava.radek20': 'vybava.radek20',
      'vybava.radek21': 'vybava.radek21',
      'vybava.radek22': 'vybava.radek22',
      'vybava.radek23': 'vybava.radek23',
      'vybava.radek24': 'vybava.radek24',
      'vybava.radek25': 'vybava.radek25',
      'vybava.radek26': 'vybava.radek26',
      'vybava.radek27': 'vybava.radek27',
      'vybava.radek28': 'vybava.radek28',
      'vybava.radek29': 'vybava.radek29',
      'vybava.radek30': 'vybava.radek30',
      'vybava.radek31': 'vybava.radek31',
      'vybava.radek32': 'vybava.radek32',
      'vybava.radek33': 'vybava.radek33',
      'vybava.radek34': 'vybava.radek34',
      'vybava.radek35': 'vybava.radek35',
      'vybava.radek36': 'vybava.radek36',
      'vybava.radek37': 'vybava.radek37',
      'vybava.radek38': 'vybava.radek38',
      'vybava.radek39': 'vybava.radek39',
      'vybava.radek40': 'vybava.radek40',
      'vybava.radek41': 'vybava.radek41',
      'vybava.radek42': 'vybava.radek42',
      'vybava.radek43': 'vybava.radek43',
      'vybava.radek44': 'vybava.radek44',
      'vybava.radek45': 'vybava.radek45',
    },
  };
}
