export interface WikiChapter {
  /** Unique id derived from file path */
  id: string;
  /** Path relative to the book folder (may contain sub-dirs / Czech chars / spaces) */
  file: string;
  /** Human-readable label shown in the sidebar */
  label: string;
}

export interface WikiBook {
  id: string;
  label: string;
  icon: string;
  chapters: WikiChapter[];
}

function ch(file: string, label: string): WikiChapter {
  return { id: file.replace(/[\s/]/g, '-'), file, label };
}

/** Auto-derive a nice label from a bare filename (no ext, no path). */
function labelOf(filename: string): string {
  return filename
    .replace(/\.md$/i, '')
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}

/** Build chapters from a flat array of filenames (best for large directories). */
function fromFiles(files: string[]): WikiChapter[] {
  return files.map(f => ch(f, labelOf(f)));
}

/** Build chapters from files inside a sub-directory of the book. */
function fromDir(dir: string, files: string[]): WikiChapter[] {
  return files.map(f => ch(`${dir}/${f}`, labelOf(f)));
}

// ─── Catalogs ────────────────────────────────────────────────────────────────

export const WIKI_CATALOG: WikiBook[] = [
  {
    id: 'prirucka-hrace',
    label: 'Příručka hráče',
    icon: 'menu_book',
    chapters: [
      ch('predmluva.md', 'Předmluva'),
      ch('uvod.md', 'Úvod'),
      ch('1-kapitola.md', '1. Postavy krok za krokem'),
      ch('2-kapitola.md', '2. Rasy'),
      ch('3-kapitola-a.md', '3a. Povolání'),
      ch('3-kapitola-b.md', '3b. Povolání (pokr.)'),
      ch('4-kapitola.md', '4. Osobnost a zázemí'),
      ch('5-kapitola.md', '5. Vybavení'),
      ch('6-kapitola.md', '6. Schopnosti'),
      ch('7-kapitola.md', '7. Hodnoty vlastností'),
      ch('8-kapitola.md', '8. Dobrodružství'),
      ch('9-kapitola.md', '9. Boj'),
      ch('10-kapitola.md', '10. Sesílání kouzel'),
      ch('11-kapitola-a.md', '11a. Kouzla'),
      ch('11-kapitola-b.md', '11b. Kouzla (pokr.)'),
      ch('dodatek-a.md', 'Dodatek A'),
      ch('dodatek-b.md', 'Dodatek B'),
      ch('dodatek-c.md', 'Dodatek C'),
      ch('dodatek-d.md', 'Dodatek D'),
      ch('dodatek-e.md', 'Dodatek E'),
    ],
  },
  {
    id: 'pruvodce-pana-jeskyne',
    label: 'Průvodce Pána Jeskyně',
    icon: 'auto_stories',
    chapters: [
      ch('uvod.md', 'Úvod'),
      ch('1-kapitola.md', '1. Svět dobrodružství'),
      ch('2-kapitola.md', '2. Vytváření světa'),
      ch('3-kapitola.md', '3. Tvorba podzemí'),
      ch('4-kapitola.md', '4. Tvorba dobrodružství'),
      ch('5-kapitola.md', '5. Vedení hry'),
      ch('6-kapitola.md', '6. Kouzelné předměty'),
      ch('7-kapitola-a.md', '7a. Poklady'),
      ch('7-kapitola-b.md', '7b. Poklady (pokr.)'),
      ch('8-kapitola.md', '8. Vedení dobrodružství'),
      ch('9-kapitola.md', '9. Herní materiály PJ'),
      ch('dodatek-A.md', 'Dodatek A'),
      ch('dodatek-B.md', 'Dodatek B'),
      ch('dodatek-C.md', 'Dodatek C'),
      ch('dodatek-D.md', 'Dodatek D'),
    ],
  },
  {
    id: 'jeskyne-a-draci',
    label: 'Jeskyně a draci',
    icon: 'castle',
    chapters: [
      ch('0-uvod.md', 'Úvod'),
      ch('1-zaklady.md', '1. Základy'),
      ch('2-tvorba-postavy.md', '2. Tvorba postavy'),
      ch('3-rasy.md', '3. Rasy'),
      ch('povolani/uvod.md',                  '4. Povolání – Úvod'),
      ch('povolani/alchymista.md',            'Povolání – Alchymista'),
      ch('povolani/barbar.md',                'Povolání – Barbar'),
      ch('povolani/bard.md',                  'Povolání – Bard'),
      ch('povolani/bojovnik.md',              'Povolání – Bojovník'),
      ch('povolani/carodej.md',               'Povolání – Čaroděj'),
      ch('povolani/cernokneznik.md',          'Povolání – Černokněžník'),
      ch('povolani/druid.md',                 'Povolání – Druid'),
      ch('povolani/klerik.md',                'Povolání – Klerik'),
      ch('povolani/kouzelnik.md',             'Povolání – Kouzelník'),
      ch('povolani/lovec-netvoru.md',         'Povolání – Lovec netvorů'),
      ch('povolani/tulak.md',                 'Povolání – Tulák'),
      ch('povolani/kombinovana-povolani.md',  'Kombinovaná povolání'),
      ch('povolani/odbornosti.md',            'Odbornosti'),
      ch('5-detaily-postavy.md', '5. Detaily postavy'),
      ch('6-vybaveni.md', '6. Vybavení'),
      ch('7-organizace-hry-a-pomucky.md', '7. Organizace hry'),
      ch('8a-hrani-hry-po-boj.md', '8a. Hraní hry'),
      ch('8b-hrani-hry-od-boj.md', '8b. Hraní hry (pokr.)'),
      ch('9-vedeni-hry.md', '9. Vedení hry'),
      ch('10a-magie-po-kouzla.md', '10a. Magie'),
      ch('10b-magie-dostupna-kouzla.md', '10b. Dostupná kouzla'),
      ch('10c-magie-kouzla-0-3.md', '10c. Kouzla 0–3'),
      ch('10d-magie-kouzla-4-9.md', '10d. Kouzla 4–9'),
      ch('11-kouzelne-predmety.md', '11. Kouzelné předměty'),
      ch('12-protivnici-a-netvori.md', '12. Protivníci a netvoři'),
      ch('13-stavy-a-nemoci.md', '13. Stavy a nemoci'),
    ],
  },
  {
    id: 'jeskyne-a-draci-doplnky',
    label: 'J&D doplňky',
    icon: 'extension',
    chapters: [
      ch('hvezdne-obory.md', 'Hvězdné obory'),
    ],
  },
  {
    id: 'xanathar',
    label: 'Xanatharův průvodce',
    icon: 'visibility',
    chapters: [
      ch('Uvod.md', 'Úvod'),
      ch('1-kapitola.md', '1. Možnosti povolání'),
      ch('2-kapitola.md', '2. Rasy'),
      ch('3-kapitola.md', '3. Kouzla'),
      ch('dodatek-A-sdilene_kampane.md', 'Dodatek A – Sdílené kampaně'),
      ch('dodatek-B-jmena.md', 'Dodatek B – Jména'),
    ],
  },
  {
    id: 'tasha',
    label: 'Tashina kotel',
    icon: 'science',
    chapters: [
      ch('Úvod a Kapitola 1 - Použití knihy (Úvod).md', 'Úvod a Kapitola 1'),
      ch('Kapitola 2 - Patroni.md', 'Kapitola 2 – Patroni'),
      ch('Kapitola 3 - Kouzla.md', 'Kapitola 3 – Kouzla'),
      ch('Kapitola 4 - Nástroje PJe.md', 'Kapitola 4 – Nástroje PJe'),
      ch('Odbornosti/Kapitola 1 - Odbornosti.md', 'Odbornosti – Kapitola 1'),
      ch('Jednotlivá povolání/Kapitola 1 - Barbar.md', 'Povolání – Barbar'),
      ch('Jednotlivá povolání/Kapitola 1 - Bard.md', 'Povolání – Bard'),
      ch('Jednotlivá povolání/Kapitola 1 - Bojovník.md', 'Povolání – Bojovník'),
      ch('Jednotlivá povolání/Kapitola 1 - Druid.md', 'Povolání – Druid'),
      ch('Jednotlivá povolání/Kapitola 1 - Hraničář.md', 'Povolání – Hraničář'),
      ch('Jednotlivá povolání/Kapitola 1 - Klerik.md', 'Povolání – Klerik'),
      ch('Jednotlivá povolání/Kapitola 1 - Kouzelník.md', 'Povolání – Kouzelník'),
      ch('Jednotlivá povolání/Kapitola 1 - Monk.md', 'Povolání – Mnich'),
      ch('Jednotlivá povolání/Kapitola 1 - Paladin.md', 'Povolání – Paladin'),
      ch('Jednotlivá povolání/Kapitola 1 - Tulák.md', 'Povolání – Tulák'),
      ch('Jednotlivá povolání/Kapitola 1 - Čaroděj.md', 'Povolání – Čaroděj'),
      ch('Jednotlivá povolání/Kapitola 1 - Čarotvůrce.md', 'Povolání – Čarotvůrce'),
      ch('Jednotlivá povolání/Kapitola 1 - Černokněžník.md', 'Povolání – Černokněžník'),
    ],
  },
  {
    id: 'dobrodruhuv-pruvodce',
    label: 'Dobrodruhův průvodce',
    icon: 'explore',
    chapters: [
      ch('kapitola-4-povolani.md', 'Kapitola 4 – Povolání'),
    ],
  },
  {
    id: 'voluv-pruvodce-netvory',
    label: 'Volův průvodce netvory',
    icon: 'pest_control',
    chapters: [
      ch('1-kapitola.md', '1. Kapitola'),
      ch('2-kapitola.md', '2. Kapitola'),
      ch('3-kapitola.md', '3. Kapitola'),
      ch('Dodatek-A.md', 'Dodatek A'),
      ch('Dodatek-B.md', 'Dodatek B'),
      ch('Dodatek-C.md', 'Dodatek C'),
      ...fromFiles([
        'Bandrhob.md','Bargest.md','Bodak.md','Chitinove.md','Demoni.md','Dinosauri.md',
        'Draeglot.md','Giralon.md','Gnolove.md','Grungove.md','Hlubinny-dedic.md',
        'Jeskynni-rybar.md','Jezibaby.md','Katoblepas.md','Ki-rin.md','Klouzavy-stopar.md',
        'Koboldi.md','Kored.md','Kraniokrysy.md','Krvokap.md','Kyjuv-zplozenec.md',
        'Lesni-kostal.md','Leukrota.md','Matucha.md','Mentalni-svedek.md','Minlok.md',
        'Morkot.md','Morsky-zplozenec.md','Mozkozrouti.md','Neogi.md','Neothelid.md',
        'Nilbog.md','Obri.md','Ohnemloci.md','Orci.md','Pastivec.md','Pozirac.md',
        'Prchlik.md','Proklety-ohar.md','Remdisnek.md','Skuruti.md','Stinovy-mastif.md',
        'Strazny-jester.md','Temnici.md','Tlinkal.md','Varguj.md','Vegepygmejove.md',
        'Xvarti.md','Yuan-tiove.md','Zabomot.md','Zrici.md',
      ]),
    ],
  },
  {
    id: 'bestiar',
    label: 'Bestiář',
    icon: 'cruelty_free',
    chapters: [
      ch('uvod.md', 'Úvod'),
      ch('dodate-a.md', 'Dodatek A'),
      ch('dodatek-b.md', 'Dodatek B'),
      ch('dodatek-c.md', 'Dodatek C'),
      ...fromFiles([
        'abolet.md','andele.md','ankheg.md','arakokra.md','azer.md','bazilisek.md',
        'behir.md','blekotajici-tlamac.md','bludicka.md','bulta.md','chimera.md',
        'chrlic.md','chuul.md','dablove.md','demoni.md','diblik.md','dinosauri.md',
        'divous.md','draci-zelva.md','draci.md','drak-stinovy.md','drakostej.md',
        'dravouk.md','dryada.md','duch.md','duergar.md','dvojnik.md','elementalove.md',
        'elfove-drowove.md','empyrean.md','ent.md','etin.md','fext.md','flamp.md',
        'fomorian.md','galeb-dur.md','geniove.md','ghulove.md','githove.md','gnolove.md',
        'gnom-hlubinny.md','goblini.md','gobri.md','golemove.md','gorgon.md','grel.md',
        'gryf.md','gryk.md','hakovec.md','harpyje.md','hipogryf.md','homunkulus.md',
        'houby.md','hrotoun.md','hydra.md','jednorozec.md','jesterci.md','jezibaby.md',
        'kambion.md','kenku.md','kentaur.md','klamopard.md','klepetnatec.md','koboldi.md',
        'kokatrice.md','kostej.md','kostlivci.md','kovatl.md','kraken.md','krapnitec.md',
        'kuo-toove.md','kyklop.md','lamie.md','litice.md','lykantropove.md','magmar.md',
        'mantikora.md','meduza.md','mefiti.md','mimik.md','minotaurus.md','modroni.md',
        'moran.md','morian.md','mozkozrout.md','mrchodravec.md','mstitel.md','mumie.md',
        'mykonidi.md','nagy.md','neviditelny-stopar.md','nocni-mura.md','noh.md','notik.md',
        'obri.md','obrneny-des.md','ohniva-lebka.md','on.md','orkove.md','otyugh.md',
        'ozivle-predmety.md','pavoucnatec.md','pegas.md','pekelny-ohar.md','peryton.md',
        'plastnik.md','plazivy-parat.md','poletucha.md','polodrak.md','polokostej.md',
        'prizrak.md','pseudodrak.md','purpurovy-cerv.md','quagot.md','raksaza.md',
        'remorazove.md','ropusak.md','rozumhlt.md','rytir-smrti.md','rzivy-netvor.md',
        'sahuagini.md','sakalodlak.md','salamandri.md','satyr.md','sfingy.md','skuruti.md',
        'sladi.md','slizy.md','sneti.md','sovodved.md','spektra.md','stin.md',
        'stitovy-strazce.md','strasak.md','striga.md','sukuba-nebo-inkubus.md','tarask.md',
        'temnoplast.md','thri-kreen.md','tlejici-valivec.md','troglodyt.md','troll.md',
        'upiri.md','vili-dracek.md','vodni-div.md','vyverna.md','xorn.md','yettiove.md',
        'yuan-tiove.md','yugoloti.md','zlobri.md','zombie.md','zrici.md',
      ]),
    ],
  },
  {
    id: 'snippets',
    label: 'Snippety a doplňky',
    icon: 'library_books',
    chapters: [
      // ── Povolání ─────────────────────────────────────────────────────────
      ...fromFiles([
        'povolani/barbar-zaklad-charakteristika.md','povolani/barbar-zaklad-schopnosti.md',
        'povolani/barbar-zaklad-prvotni-cesty.md','povolani/bard-zaklad-charakteristika.md',
        'povolani/bard-zaklad-schopnosti.md','povolani/bard-zaklad-koleje.md',
        'povolani/bojovnik-zaklad-charakteristika.md','povolani/bojovnik-zaklad-schopnosti.md',
        'povolani/bojovnik-zaklad-archetypy.md','povolani/car-zaklad-charakteristika.md',
        'povolani/car-zaklad-schopnosti.md','povolani/car-zaklad-puvody.md',
        'povolani/cern-zaklad-charakteristika.md','povolani/cern-zaklad-schopnosti.md',
        'povolani/cern-zaklad-patroni.md','povolani/cern-zaklad-vzyvani.md',
        'povolani/druid-zaklad-charakteristika.md','povolani/druid-zaklad-schopnosti.md',
        'povolani/druid-zaklad-kruhy.md','povolani/hranicar-zaklad-charakteristika.md',
        'povolani/hranicar-zaklad-schopnosti.md','povolani/hranicar-zaklad-archetypy.md',
        'povolani/klerik-zaklad-charakteristika.md','povolani/klerik-zaklad-schopnosti.md',
        'povolani/klerik-zaklad-domeny.md','povolani/kouzelnik-zaklad-charakteristika.md',
        'povolani/kouzelnik-zaklad-schopnosti.md','povolani/kouzelnik-zaklad-tradice.md',
        'povolani/lovec-jad-schopnosti.md','povolani/mnich-zaklad-charakteristika.md',
        'povolani/mnich-zaklad-schopnosti.md','povolani/mnich-zaklad-cesty.md',
        'povolani/paladin-zaklad-charakteristika.md','povolani/paladin-zaklad-schopnosti.md',
        'povolani/paladin-zaklad-prisahy.md','povolani/tulak-zaklad-charakteristika.md',
        'povolani/tulak-zaklad-schopnosti.md','povolani/tulak-zaklad-archetypy.md',
      ]),
      // ── Obory ────────────────────────────────────────────────────────────
      ...fromFiles([
        'obory/barbar-cesta-berserkra.md','obory/barbar-cesta-totemoveho-valecnika.md',
        'obory/bard-kolej-znalosti.md','obory/bard-kolej-odvahy.md',
        'obory/bojovnik-archetyp-sampion.md','obory/bojovnik-archetyp-caroknecht.md',
        'obory/klerik-domena-zivot.md','obory/klerik-domena-svetlo.md',
        'obory/klerik-domena-valka.md','obory/klerik-domena-priroda.md',
        'obory/druid-kruh-mesice.md','obory/druid-kruh-zeme.md',
        'obory/hranicar-archetyp-lovec.md','obory/hranicar-archetyp-pan-zvirat.md',
        'obory/kouzelnik-tradice-zaklinani.md','obory/kouzelnik-tradice-iluze.md',
        'obory/kouzelnik-tradice-nekromancie.md','obory/kouzelnik-tradice-vyvolani.md',
        'obory/paladin-prisaha-oddanosti.md','obory/paladin-prisaha-pomsty.md',
        'obory/tulak-archetyp-zlodej.md','obory/tulak-archetyp-vrah.md',
        'obory/tulak-archetyp-vykradac-hrobek.md',
      ]),
      // ── Kouzla ───────────────────────────────────────────────────────────
      ...fromDir('kouzla', [
        'abi-dalzimovo-straslive-sucho.md','aganazzaruv-zar.md','antimagicke-pole.md',
        'antipatie-nebo-sympatie.md','antropomancie.md','astralni-projekce.md',
        'aura-cistoty.md','aura-vitality.md','aura-zivota.md','azyl.md',
        'bajny-lucistnik.md','barevna-koule.md','barevna-sprska.md','bariera-cepeli.md',
        'besneni.md','bigbyho-ruka.md','blesk.md','bleskovy-sip.md','bludiste.md',
        'boure-odplaty.md','bourna-koule.md','bozi-chram.md','bozi-dohled.md',
        'bozske-slovo.md','brana.md','carodejnicky-blesk.md','casovana-ohniva-koule.md',
        'cejchovaci-uder.md','cepel-zeleneho-plamene.md','cerny-jed.md',
        'chaoticky-blesk.md','chapadlo.md','chuze-po-vode.md','chuze-stromy.md',
        'dalekokrok.md','denni-svetlo.md','dimenzionalni-dvere.md','divoke-roztrhani.md',
        'divotvorstvi-jad.md','divotvorstvi.md','dlouhokrok.md','dobruvka.md',
        'draci-dech.md','drawmijovo-okamzite-privolani.md','drobna-iluze-jad.md',
        'drobna-iluze.md','drobny-sluzebnik.md','druidovstvi.md','druidstvi-jad.md',
        'duchovni-zbran.md','dunive-ostri.md','dustojny-odpocinek.md','dvojnik.md',
        'elementalni-erupce.md','etericnost.md','evardova-cerna-chapadla.md',
        'falesny-zivot.md','fantom.md','fascinuj.md','fata-morgana.md',
        'hadarova-touha.md','hadarovy-paze.md','hadi-ustknuti.md','hexensus.md',
        'hlas-boure.md','hlas-umiracku.md','hlidej-a-strez.md','hmyzi-zhouba.md',
        'hnev-prirody.md','hnev-zivlu.md','hniloba.md','horici-oblak.md',
        'horici-ruce.md','hrdinstvi.md','hromadna-promena.md','hromadna-sugesce.md',
        'hromadne-lecive-slovo.md','hromadne-prestrojeni.md','hromadne-uzdraveni.md',
        'hromadne-zhojeni-zraneni.md','hromokrok.md','hromova-vlna.md','hromovy-uder.md',
        'hvezdna-koruna.md','hypnoticky-vzor.md','iluzorni-drak.md','iluzorni-text.md',
        'iluzorni-vezeni.md','jasnozrivost.md','jazyky.md','jedovata-koule.md',
        'jedovata-sprska.md','kamenna-kuze.md','kamenna-zed.md','kamenny-plast.md',
        'katapult.md','kejkle-jad.md','kejkle.md','klamny-prostor.md','kletba.md',
        'klon.md','kordon-sipu.md','koreny-omotani.md','koruna-silenstvi.md',
        'kosti-zeme.md','koule-nezranitelnosti.md','kouzelny-oblazek.md',
        'krizakova-pelerina.md','kruh-moci.md','kruh-smrti.md','krupobiti-trnu.md',
        'kurokuze.md','kuzel-mrazu.md','kyselinova-koule.md','leciva-modlitba.md',
        'lecive-slovo.md','lecivy-duch.md','ledova-boure.md','ledova-zed.md',
        'ledovy-nuz.md','ledovy-plast.md','leomunidova-chatka.md',
        'leomunidova-tajna-truhla.md','let.md','levitace.md','lovcova-marka.md',
        'maelstrom.md','magicka-strela.md','magicka-usta.md','magicka-zbran.md',
        'magicky-kruh.md','magova-ruka-jad.md','magova-ruka.md','magova-zbroj.md',
        'majak-nadeje.md','maso-na-kamen.md','maxmilianova-hlinena-ruka.md',
        'melfovy-meteorky.md','melfuv-kyselinovy-sip.md','mentalni-bodec.md',
        'mentalni-uder.md','mesicni-paprsek.md','mihotani.md','mluv-s-mrtvymi.md',
        'mluv-s-rostlinami.md','mluv-se-zviraty.md','mluva-sfer.md','mlzna-podoba.md',
        'mlzny-krok.md','mocna-neviditelnost.md','mocne-navraceni.md','mocny-hrad.md',
        'mordenkainenova-soukroma-svatyne.md','mordenkainenuv-mec.md',
        'mordenkainenuv-velkolepy-dum.md','mordenkainenuv-verny-pes.md',
        'mrazivy-dotyk.md','mrazivy-paprsek.md','mysticka-brana.md','mysticke-oko.md',
        'mysticky-zamek.md','najdi-cestu.md','najdi-honosnejsiho-ore.md',
        'najdi-jed-a-nemoc.md','najdi-magii.md','najdi-ore.md','najdi-pasti.md',
        'najdi-predmet.md','najdi-pritelicka.md','najdi-tvora.md','najdi-zlo-a-dobro.md',
        'najdi-zvirata-a-rostliny.md','nakaza.md','naplanovana-iluze.md',
        'napodobenina.md','navadeci-blesk.md','nebepis.md','nelibozvucny-sepot.md',
        'nemesis.md','nesnesitelna-temnota.md','neuveritelny-puvab.md',
        'neviditelnost.md','neviditelny-sluzebnik.md','nezjistitelnost.md',
        'nezranitelnost.md','niciva-vlna.md','nizsi-navraceni.md','nutkani.md',
        'nystulova-magicka-aura.md','obkliceni.md','oblak-dyk.md','oblak-mlhy.md',
        'oblak-smrti.md','obrad.md','obri-hmyz.md','obrozeni.md',
        'ochrana-pred-energii.md','ochrana-pred-jedem.md','ochrana-pred-zlem-a-dobrem.md',
        'ochrance-prirody.md','ocisti-jidlo-a-piti.md','odhal-myslenky.md',
        'odolani-jad.md','odolani.md','odolej-zivlum.md','odpocinkova-hymna.md',
        'odporne-zareni.md','ohniva-boure.md','ohniva-cepel.md','ohniva-koule.md',
        'ohniva-strela.md','ohniva-zed.md','ohnivy-stit.md','omrzliny.md',
        'oprava-jad.md','oprava.md','oslepujici-uder.md','otilukova-mraziva-koule.md',
        'otilukova-nepoddajna-koule.md','otoc-gravitaci.md','otuv-neodolatelny-tanec.md',
        'ovladni-plameny.md','ovladni-pocasi.md','ovladni-vitr.md','ovladni-vodu.md',
        'oziv-mrtveho.md','ozivle-predmety.md','pachnouci-oblak.md',
        'paprsek-otraveni.md','paprsek-slabosti.md','pavouci-splh.md','pavucina.md',
        'pekelne-pokarani.md','pekelne-volani.md','pisecna-zed.md','plamenne-sipy.md',
        'plamenny-plast.md','plamenny-uder.md','planouci-koule.md','plast-zmaru.md',
        'podminecnost.md','podpora.md','podrob-nestvuru.md','podrob-osobu.md',
        'podrob-zvire.md','pohled-smrti.md','pohni-zemi.md','polapujici-uder.md',
        'polosfera.md','pomaly-pad.md','poplach.md','porozumeni-jazykum.md',
        'poryv-vetru.md','poselstvi.md','posileni-dovednosti.md','poslys-myty.md',
        'posvatna-puda.md','posvatny-haj.md','posvatny-plamen.md','pozehnani.md',
        'prani.md','prasny-vir.md','pratele.md','pratelstvi-zvirat.md',
        'pravdive-videni.md','predstirej-smrt.md','predtucha.md','predvidani.md',
        'prelud.md','premen-kamen.md','presny-uder-jad.md','presny-uder.md',
        'prestrojeni.md','presun-rostlinami.md','presun-sferami.md','presun-zivota.md',
        'prilivova-vlna.md','prizen-bohu.md','prizracni-strazci.md','prizracny-or.md',
        'probuzeni.md','projdi-beze-stop.md','projdi-zdi.md','promen.md',
        'protikouzlo.md','prst-smrti.md','prvotni-bariera.md','pyrotechnika.md',
        'raryho-telepaticke-pouto.md','regenerace.md','reinkarnace.md',
        'retezy-upoutani.md','roj-meteoritu.md','roj-snehovych-kouli.md','rozkaz.md',
        'rozklad.md','rozmazani.md','rozpal-kov.md','rozpras.md','rozptyl-magii.md',
        'rozptyl-zlo-a-dobro.md','roztristeni.md','rozvetveny-blesk.md',
        'rust-rostlin.md','rychlost.md','rychly-toulec.md','sadlo.md',
        'schranka-zivota.md','sejmi-kletbu.md','sen.md','sezehujici-paprsek.md',
        'sfericka-vazba.md','sfericky-spojenec.md','sila-fenixe.md','silova-klec.md',
        'skok.md','skutecna-promena.md','slabomyslnost.md','sledovani.md',
        'slepota-nebo-hluchota.md','slidive-oko.md','slizky-uder.md','slofik.md',
        'slovo-moci-bolest.md','slovo-moci-ochrom.md','slovo-moci-uzdrav.md',
        'slovo-moci-zabij.md','slovo-navratu.md','slovo-svetla.md','slunecni-erupce.md',
        'slunecni-paprsek.md','smrst.md','smycka.md','sokujici-sevreni.md',
        'spalujici-uder.md','spanek.md','spatri-neviditelne.md','spektralni-sprska.md',
        'spektralni-zed.md','spesny-ustup.md','spojeni-s-prirodou.md','spojeni.md',
        'stin-moilu.md','stinocepel.md','stit-proti-zivym.md','stit-viry.md','stit.md',
        'strach.md','strazce-viry.md','strazne-pouto.md','strazny-vichr.md',
        'strazny-znak.md','stvor-homunkula.md','stvor-jidlo-a-vodu.md',
        'stvor-nebo-znic-vodu.md','stvor-nemrtve.md','stvor-plamen.md','stvor-taborak.md',
        'sugesce.md','sukovice.md','svata-aura.md','svecena-zbran.md','svetelna-zed.md',
        'svetlo-jad.md','svetlo.md','svolej-blesky.md','symbol.md','synapticky-sum.md',
        'tajemny-vysleh.md','tancici-svetla-jad.md','tancici-svetla.md',
        'tanec-mrtvych.md','tasin-desivy-smich.md','telekineze.md',
        'telepaticky-vykrik.md','telepatie.md','teleport.md','teleportacni-kruh.md',
        'tenserova-promena.md','tenseruv-levitujici-disk.md','ticho.md','tichy-obraz.md',
        'tma.md','trik-s-lanem.md','trnova-zed.md','trnovy-bic.md','trny.md',
        'tsunami.md','tvaruj-kamen.md','tvaruj-vodu.md','tvaruj-zemi.md','tvorba.md',
        'ubrousku-prostri-se.md','uchvacujici-reva.md','uder-oceloveho-vichru.md',
        'uder-zloby.md','uklidni-emoce.md','ukol.md','ukryj-mysl.md','upaleni.md',
        'upiri-dotyk.md','urceni.md','usetri-umirajiciho-jad.md','usetri-umirajiciho.md',
        'usvit.md','uvezneni.md','uvrhini-kletbu.md','uzdrav.md','uzemneni.md',
        'vabnicka-blesku.md','vecny-plamen.md','vedeni-jad.md','vedeni.md',
        'vejdi-do-kamene.md','velky-obraz.md','vesteni.md','vetrna-chuze.md',
        'vetrna-zed.md','vetrny-plast.md','vezeni-duse.md','videni-ve-tme.md',
        'vili-ohen.md','vlastni-obraz.md','vodnata-koule.md','vodni-dech.md',
        'vodni-zed.md','volnost.md','vybuch-mece.md','vybuchujici-zeme.md',
        'vycerpani.md','vynuceny-duel.md','vypuzeni.md','vypuzujici-uder.md',
        'vyrecnosti.md','vystras.md','vyvolej-elementala.md','vyvolej-lesni-bytosti.md',
        'vyvolej-mensi-demony.md','vyvolej-mocneho-demona.md','vyvolej-nebestana.md',
        'vyvolej-nizsi-elementaly.md','vyvolej-palbu.md','vyvolej-salvu.md',
        'vyvolej-vilu.md','vyvolej-zvirata.md','vzkriseni.md','zahaleni.md',
        'zahrmeni.md','zakaz.md','zaklep.md','zamoreni.md','zaplava-negativni-energie.md',
        'zapleteni.md','zastav-cas.md','zatres-zemi.md','zavan.md','zavratny-uder.md',
        'zbroj-agathysu.md','zed-sily.md','zefyruv-uder.md','zemetreseni.md',
        'zhoj-zraneni.md','zhotov.md','zhouba.md','zivelna-zbran.md','zivelna-zkaza.md',
        'zkriveni-prostoru.md','zle-oko.md','zlepsi-vlastnost.md','zlomyslny-vysmech.md',
        'zmam-obludu.md','zmam-osobu.md','zmatek.md','zmen-pamet.md','zmen-svuj-tvar.md',
        'zmena-podoby.md','zmrtvychvstani.md','zmrzly-dest.md','znameni-proti-cepelim.md',
        'znameni-proti-smrti.md','znehybni-nestvuru.md','znehybni-osobu.md',
        'znovuzrozeni.md','zona-pravdy.md','zpomaleni.md','zprava-jad.md','zprava.md',
        'zpusob-zraneni.md','zran.md','zrcadlovy-obraz.md','zvetseni-nebo-zmenseni.md',
        'zvireci-podoba.md','zvireci-posel.md','zvireci-pouto.md','zvireci-smysly.md',
      ]),
    ],
  },
];

